/* [artikel, kelime, çoğul, türkçe, örnek cümle, tür, örnek çevirisi]
   tür: n=isim v=fiil a=sıfat x=diğer
   Sıra dersleri belirler (30 kelimelik gruplar). Kimlik "artikel|kelime" olduğu için
   bir kelimenin yazımını değiştirirsen eski kimliği ID_ALIASES içine ekle, ilerlemesi taşınsın. */
const DATA = [
["die","Adresse","-n","adres","Können Sie mir seine Adresse sagen?","n","Bana onun adresini söyleyebilir misiniz?"],
["der","Apfel","¨","elma","Ein Pfund Äpfel, bitte.","n","Yarım kilo elma lütfen."],
["die","Arbeit","-en","iş","Mein Bruder sucht Arbeit.","n","Kardeşim iş arıyor."],
["der","Arzt","¨-e","doktor","Morgen habe ich einen Termin beim Arzt.","n","Yarın doktorla randevum var."],
["das","Auge","-n","göz","Er hat blaue Augen.","n","Mavi gözleri var."],
["der","Ausweis","-e","kimlik kartı","Hier ist mein Ausweis.","n","Bu benim kimliğim."],
["das","Auto","-s","araba","Er kommt mit dem Auto.","n","Arabayla geliyor."],
["die","Bäckerei","-en","fırın","Ich geh mal schnell zur Bäckerei.","n","Hemen fırına bir uğrayayım."],
["der","Bahnhof","¨-e","tren istasyonu","Komme ich hier zum Bahnhof?","n","Buradan tren istasyonuna gidebilir miyim?"],
["die","Bank","-en","banka","Die Bank schließt schon um vier Uhr.","n","Banka saat dörtte kapanıyor."],
["der","Baum","¨-e","ağaç","Vorsicht, fahr nicht an den Baum!","n","Dikkat, ağaca çarpma!"],
["das","Bett","-en","yatak","Wir brauchen noch ein Kinderbett.","n","Bir de çocuk yatağına ihtiyacımız var."],
["das","Bild","-er","resim","Hast du ein Bild von deinem Sohn?","n","Oğlunun resmi var mı?"],
["die","Blume","-n","çiçek","Gefallen dir die Blumen?","n","Çiçekleri beğendin mi?"],
["der","Brief","-e","mektup","Haben Sie einen Brief für mich?","n","Bana mektup var mı?"],
["das","Brot","-e","ekmek","Haben Sie auch Weißbrot?","n","Beyaz ekmeğiniz de var mı?"],
["der","Bruder","¨","erkek kardeş","Sein Bruder arbeitet auch hier.","n","Kardeşi de burada çalışıyor."],
["das","Buch","¨-er","kitap","Gute Bücher sind oft sehr teuer.","n","İyi kitaplar genellikle çok pahalıdır."],
["der","Bus","-se","otobüs","Wann kommt der nächste Bus?","n","Bir sonraki otobüs ne zaman gelecek?"],
["die","Ecke","-n","köşe","An der nächsten Ecke links.","n","Bir sonraki köşeden sola."],
["das","Ei","-er","yumurta","Möchtest du ein Ei zum Frühstück?","n","Kahvaltıda yumurta ister misin?"],
["die","Fahrkarte","-n","bilet","Hast du schon eine Fahrkarte?","n","Biletini aldın mı?"],
["das","Fahrrad","¨-er","bisiklet","Fährst du mit dem Fahrrad?","n","Bisikletle mi gidiyorsun?"],
["die","Familie","-n","aile","Meine Familie lebt in Spanien.","n","Ailem İspanya'da yaşıyor."],
["die","Farbe","-n","renk","Die Farbe gefällt mir gut.","n","Rengi beğendim."],
["der","Fehler","-","hata","Diesen Fehler mache ich immer.","n","Bu hatayı hep yapıyorum."],
["der","Film","-e","film","Ich möchte gern diesen Film sehen.","n","Bu filmi görmek isterim."],
["die","Flasche","-n","şişe","Eine Flasche Wasser, bitte.","n","Bir şişe su lütfen."],
["das","Fleisch","","et","Fleisch mag ich nicht.","n","Eti sevmiyorum."],
["der","Flughafen","¨","havalimanı","Kannst du mich zum Flughafen bringen?","n","Beni havaalanına götürebilir misin?"],
["das","Formular","-e","form","Sie müssen dieses Formular ausfüllen.","n","Bu formu doldurmalısınız."],
["die","Frage","-n","soru","Ich habe eine Frage.","n","Bir sorum var."],
["der","Freund","-e","arkadaş","Das ist ein Freund von mir.","n","Bu benim bir arkadaşım."],
["das","Frühstück","","kahvaltı","Möchtest du ein Ei zum Frühstück?","n","Kahvaltıda yumurta ister misin?"],
["der","Garten","¨","bahçe","Wir haben leider keinen Garten.","n","Maalesef bahçemiz yok."],
["der","Gast","¨-e","misafir","Am Wochenende haben wir Gäste.","n","Hafta sonu misafirlerimiz var."],
["der","Geburtstag","-e","doğum günü","Herzlichen Glückwunsch zum Geburtstag!","n","Doğum günün kutlu olsun!"],
["das","Geld","","para","Hast du noch Geld?","n","Hiç paran kaldı mı?"],
["das","Gemüse","","sebze","Gemüse brauchen wir auch noch.","n","Sebze de almamız lazım."],
["das","Geschenk","-e","hediye","Danke für das schöne Geschenk.","n","Güzel hediye için teşekkür ederim."],
["das","Glas","¨-er","bardak","Bitte noch ein Glas Wasser!","n","Bir bardak daha su lütfen!"],
["das","Haar","-e","saç","Sie hat lange Haare.","n","Uzun saçları var."],
["die","Hand","¨-e","el","Er gibt mir die Hand.","n","Benimle tokalaşıyor."],
["das","Handy","-s","cep telefonu","Bitte die Handys ausmachen!","n","Lütfen cep telefonlarınızı kapatın!"],
["das","Haus","¨-er","ev","Ich gehe jetzt nach Hause.","n","Şimdi eve gidiyorum."],
["der","Herd","-e","ocak","In der neuen Küche fehlt noch der Herd.","n","Yeni mutfakta ocak hâlâ yok."],
["das","Hotel","-s","otel","Wir sind in einem Hotel am Meer.","n","Deniz kenarında bir oteldeyiz."],
["der","Hund","-e","köpek","Der Hund ist noch jung.","n","Köpek henüz genç."],
["die","Jacke","-n","ceket","Zieh dir eine Jacke an. Es ist kalt.","n","Bir ceket giy. Hava soğuk."],
["der","Kaffee","","kahve","Zum Frühstück trinke ich immer Kaffee.","n","Kahvaltıda her zaman kahve içerim."],
["die","Kartoffel","-n","patates","Für Pommes frites braucht man Kartoffeln.","n","Patates kızartması için patates gerekir."],
["die","Kasse","-n","kasa","Zahlen Sie bitte an der Kasse.","n","Lütfen kasada ödeyin."],
["das","Kind","-er","çocuk","Wie viele Kinder haben Sie?","n","Kaç çocuğunuz var?"],
["das","Kino","-s","sinema","Wir gehen heute ins Kino.","n","Bugün sinemaya gideceğiz."],
["der","Koffer","-","bavul","Ist das Ihr Koffer?","n","Bu sizin bavulunuz mu?"],
["der","Kopf","¨-e","baş","Mein Kopf tut weh!","n","Başım ağrıyor!"],
["die","Küche","-n","mutfak","Der neue Herd kommt in die Küche.","n","Yeni ocak mutfağa konuyor."],
["der","Kuchen","-","kek, pasta","Ich nehme ein Stück Kuchen.","n","Bir parça kek alacağım."],
["der","Kühlschrank","¨-e","buzdolabı","Die Milch steht im Kühlschrank.","n","Süt buzdolabında."],
["das","Land","¨-er","ülke","Italien ist ein schönes Land.","n","İtalya güzel bir ülke."],
["der","Lehrer","-","öğretmen","Unser Lehrer heißt Herr Müller.","n","Öğretmenimizin adı Bay Müller."],
["das","Licht","-er","ışık","Mach bitte das Licht an!","n","Lütfen ışığı aç!"],
["das","Lied","-er","şarkı","Welches ist dein Lieblingslied?","n","En sevdiğin şarkı hangisi?"],
["das","Mädchen","-","kız çocuğu","Junge oder Mädchen?","n","Erkek mi kız mı?"],
["das","Meer","-e","deniz","Wir machen Urlaub am Meer.","n","Deniz kenarında tatile gidiyoruz."],
["die","Miete","-n","kira","Die Miete für diese Wohnung ist 600 Euro.","n","Bu dairenin kirası 600 Euro'dur."],
["die","Milch","","süt","Trinken Sie den Kaffee mit Milch?","n","Kahveyi sütlü mü içersiniz?"],
["die","Mutter","¨","anne","Meine Mutter heißt Eva.","n","Annemin adı Eva."],
["der","Name","-n","isim","Mein Name ist Thomas Schmidt.","n","Adım Thomas Schmidt."],
["das","Obst","","meyve","Im Sommer ist das Obst billig.","n","Yaz aylarında meyveler ucuzdur."],
["der","Pass","¨-e","pasaport","Im Hotel brauchst du deinen Pass.","n","Otelde pasaportuna ihtiyacın olacak."],
["die","Polizei","","polis","Holen Sie die Polizei!","n","Polisi çağırın!"],
["die","Post","","postane","Wo ist die Post, bitte?","n","Postane nerede, lütfen?"],
["die","Rechnung","-en","hesap, fatura","Die Rechnung, bitte.","n","Hesap, lütfen."],
["der","Regen","","yağmur","Bei diesem Regen gehe ich nicht raus.","n","Bu yağmurda dışarı çıkmayacağım."],
["die","Reise","-n","seyahat","Wir machen eine Reise nach Österreich.","n","Avusturya'ya bir geziye çıkıyoruz."],
["der","Schlüssel","-","anahtar","Ich gebe Ihnen den Zimmerschlüssel.","n","Size oda anahtarını veriyorum."],
["der","Schrank","¨-e","dolap","Die Gläser stehen im Schrank.","n","Bardaklar dolapta."],
["der","Schuh","-e","ayakkabı","Zieh die Schuhe aus!","n","Ayakkabılarını çıkar!"],
["die","Schule","-n","okul","Meine Tochter geht schon in die Schule.","n","Kızım zaten okula gidiyor."],
["die","Schwester","-n","kız kardeş","Meine Schwester kommt am Dienstag.","n","Kız kardeşim salı günü geliyor."],
["die","Sonne","","güneş","Die Sonne scheint.","n","Güneş parlıyor."],
["die","Sprache","-n","dil","Welche Sprachen sprichst du?","n","Hangi dilleri konuşuyorsun?"],
["die","Stadt","¨-e","şehir","Heidelberg ist eine alte Stadt.","n","Heidelberg eski bir şehir."],
["die","Straße","-n","cadde, sokak","In welcher Straße wohnen Sie?","n","Hangi sokakta oturuyorsunuz?"],
["die","Stunde","-n","saat (süre)","Ich bin in einer Stunde zurück.","n","Bir saat sonra döneceğim."],
["die","Tasche","-n","çanta","Die Schlüssel sind in der Tasche.","n","Anahtarlar çantada."],
["der","Tee","","çay","Ich trinke morgens immer Tee.","n","Sabahları mutlaka çay içerim."],
["der","Termin","-e","randevu","Am besten machen wir sofort einen Termin.","n","En iyisi hemen bir randevu alalım."],
["der","Tisch","-e","masa","Die Fotos liegen auf dem Tisch.","n","Fotoğraflar masanın üstünde."],
["die","Tochter","¨","kız evlat","Das ist meine Tochter Katharina.","n","Bu benim kızım Katharina."],
["die","Uhr","-en","saat","Es ist vier Uhr.","n","Saat dört."],
["der","Urlaub","-e","tatil","Ich nehme im September Urlaub.","n","Eylül ayında tatile çıkıyorum."],
["der","Vater","¨","baba","Mein Vater ist Arbeiter.","n","Babam işçi."],
["das","Wasser","","su","Ein Glas Wasser, bitte.","n","Bir bardak su lütfen."],
["das","Wetter","","hava (durumu)","Wir hatten schlechtes Wetter.","n","Hava kötüydü."],
["die","Wohnung","-en","daire, ev","Die Wohnung hat drei Zimmer.","n","Dairenin üç odası var."],
["das","Wort","¨-er","kelime","Ich kenne das Wort nicht.","n","Kelimeyi bilmiyorum."],
["die","Zeitung","-en","gazete","Ich lese gern Zeitung.","n","Gazete okumayı severim."],
["das","Zimmer","-","oda","Das Zimmer ist groß.","n","Oda büyük."],
["der","Zug","¨-e","tren","Ich fahre gern mit dem Zug.","n","Trenle seyahat etmeyi seviyorum."],
["","abholen","","(birini) almak","Wir müssen noch meinen Bruder abholen.","v","Hala kardeşimi almamız gerekiyor."],
["","anrufen","","telefon etmek","Kann man Sie anrufen?","v","Size telefonla ulaşılabilir mi?"],
["","arbeiten","","çalışmak","Wo arbeiten Sie?","v","Nerede çalışıyorsun?"],
["","aufstehen","","kalkmak","Ich muss immer um vier Uhr aufstehen.","v","Hep saat dörtte kalkmak zorundayım."],
["","bezahlen","","ödemek","Wo muss ich bezahlen?","v","Nerede ödeme yapmam gerekiyor?"],
["","bleiben","","kalmak","Ich bleibe heute zu Hause.","v","Bugün evde kalacağım."],
["","brauchen","","ihtiyaç duymak","Brauchst du die Zeitung noch?","v","Gazeteye hâlâ ihtiyacın var mı?"],
["","einkaufen","","alışveriş yapmak","Ich muss noch für morgen einkaufen.","v","Yarın için daha alışveriş yapmam lazım."],
["","essen","","yemek yemek","Was gibt es zu essen?","v","Yemekte ne var?"],
["","fahren","","(araçla) gitmek","Ich fahre mit dem Auto zur Arbeit.","v","Arabayla işe gidiyorum."],
["","fragen","","sormak","Er möchte Sie etwas fragen.","v","Size bir şey sormak istiyor."],
["","gehen","","gitmek","Ich muss zum Arzt gehen.","v","Doktora gitmeliyim."],
["","helfen","","yardım etmek","Können Sie mir helfen, bitte?","v","Bana yardım edebilir misiniz lütfen?"],
["","kaufen","","satın almak","Tim kauft sich ein neues Auto.","v","Tim kendine yeni bir araba alıyor."],
["","kochen","","yemek pişirmek","Herr Georgi kann gut kochen.","v","Bay Georgi iyi yemek pişirebilir."],
["","lernen","","öğrenmek","Wie lange lernen Sie schon Deutsch?","v","Ne zamandır Almanca öğreniyorsunuz?"],
["","lesen","","okumak","Ich lese ein Buch.","v","Bir kitap okuyorum."],
["","schlafen","","uyumak","Ich schlafe meistens acht Stunden.","v","Genellikle sekiz saat uyurum."],
["","schreiben","","yazmak","Er schreibt jeden Tag viele E-Mails.","v","Her gün çok sayıda e-posta yazıyor."],
["","sprechen","","konuşmak","Kann ich mit Herrn Klein sprechen?","v","Bay Klein'la konuşabilir miyim?"],
["","trinken","","içmek","Möchtest du etwas trinken?","v","İçecek bir şey ister misin?"],
["","verstehen","","anlamak","Können Sie mich verstehen?","v","Beni anlayabiliyor musunuz?"],
["","wohnen","","oturmak, yaşamak","Ich wohne in München.","v","Münih'te yaşıyorum."],
["","alt","","yaşlı, eski","Mein Auto ist schon sehr alt.","a","Arabam zaten çok eski."],
["","billig","","ucuz","Die Jacke kostet nur 10 Euro! Die ist aber billig!","a","Ceketin fiyatı sadece 10 Euro! Ama ucuz!"],
["","teuer","","pahalı","Das ist mir zu teuer.","a","Bu benim için çok pahalı."],
["","groß","","büyük","Frankfurt ist eine große Stadt.","a","Frankfurt büyük bir şehir."],
["","klein","","küçük","Eltville ist eine kleine Stadt am Rhein.","a","Eltville, Ren kıyısında küçük bir kasabadır."],
["","schnell","","hızlı","Er fährt schnell.","a","Hızlı sürüyor."],
["","müde","","yorgun","Ich bin müde. Ich gehe schlafen.","a","Yorgunum. Yatmaya gidiyorum."],
["","krank","","hasta","Ich kann heute nicht kommen, ich bin krank.","a","Bugün gelemeyeceğim, hastayım."],
["","leicht","","kolay, hafif","Der Koffer ist leicht.","a","Bavul hafif."],
["","schwer","","zor, ağır","Ist Ihr Gepäck sehr schwer?","a","Bagajınız çok mu ağır?"],
["","neu","","yeni","Wir haben eine neue Wohnung.","a","Yeni bir dairemiz var."],
["","gestern","","dün","Gestern war ich krank.","x","Dün hastaydım."],
["","heute","","bugün","Heute ist ein schöner Tag.","x","Bugün güzel bir gün."],
["","morgen","","yarın","Morgen beginnt die Schule um 10 Uhr.","x","Yarın okul saat 10'da başlıyor."],
["","immer","","her zaman","Frau Bast kommt immer zu spät.","x","Bayan Bast her zaman geç kalır."],
["","leider","","maalesef","Leider kann ich nicht kommen.","x","Maalesef gelemiyorum."],
["","vielleicht","","belki","Ich komme vielleicht mit dem Bus.","x","Belki otobüsle gelirim."],
["","ab","","itibaren","Ab morgen muss ich arbeiten.","x","Yarından itibaren çalışmam gerekiyor."],
["","aber","","ama","Ich bin oft im Büro, aber nur für wenige Stunden.","x","Sık sık ofisteyim ama sadece birkaç saatliğine."],
["","abfahren","","hareket etmek, yola çıkmak","Wir fahren um zwölf Uhr ab.","v","Saat on ikide yola çıkıyoruz."],
["die","Abfahrt","-en","kalkış","Vor der Abfahrt rufe ich an.","n","Yola çıkmadan önce ararım."],
["","abgeben","","teslim etmek; vermek","Ich muss meine Schlüssel abgeben.","v","Anahtarlarımı teslim etmem gerekiyor."],
["der","Absender","-","gönderen","Da ist ein Brief für dich ohne Absender.","n","Burada sana göndereni yazmayan bir mektup var."],
["die","Achtung","","dikkat","Achtung! Das dürfen Sie nicht tun.","n","Dikkat! Bunu yapmanız yasak."],
["","alle","","hepsi, bütün","Alle meine Freunde kommen zur Party.","x","Bütün arkadaşlarım partiye geliyor."],
["","allein","","yalnız","Er kommt allein.","a","Yalnız geliyor."],
["","also","","yani","Also, es ist so: ...","x","Yani durum şöyle: ..."],
["das","Alter","","yaş","Alter: 26 Jahre.","n","Yaş: 26."],
["","an","","-e/-a; yanında","Fahren Sie an der nächsten Straße nach rechts.","x","Bir sonraki sokaktan sağa dönün."],
["","anbieten","","ikram etmek; teklif etmek","Was darf ich dir anbieten?","v","Sana ne ikram edebilirim?"],
["das","Angebot","-e","teklif; indirim","Heute sind Sportschuhe im Angebot.","n","Bugün spor ayakkabılar indirimde."],
["","andere","","diğer, başka","Willst du diese Jacke oder die andere?","x","Bu ceketi mi istiyorsun, yoksa diğerini mi?"],
["","anfangen","","başlamak","Hier fängt die Bahnhofstraße an.","v","Bahnhofstrasse burada başlıyor."],
["der","Anfang","¨-e","başlangıç","Sie wohnt am Anfang der Straße.","n","Sokağın başında yaşıyor."],
["","anklicken","","tıklamak","Da musst du dieses Wort anklicken.","v","Bu kelimeye tıklaman gerekiyor."],
["","ankommen","","varmak","Wann kommt dieser Zug in Hamburg an?","v","Bu tren Hamburg'a ne zaman varacak?"],
["die","Ankunft","¨-e","varış","Auf diesem Plan steht nur die Ankunft der Flüge.","n","Bu planda yalnızca uçakların varış saatleri yazıyor."],
["","ankreuzen","","işaretlemek (çarpı ile)","Auf dem Formular müssen Sie an mehreren Stellen etwas ankreuzen.","v","Formda birkaç yere çarpı koymanız gerekiyor."],
["","anmachen","","açmak (ışık, cihaz)","Mach bitte das Licht an!","v","Lütfen ışığı aç!"],
["","anmelden","","kaydolmak","Wo kann ich mich anmelden?","v","Nereye kayıt olabilirim?"],
["die","Anmeldung","-en","kayıt","Eine Anmeldung für diesen Kurs ist nicht mehr möglich.","n","Bu kursa kayıt artık mümkün değildir."],
["die","Anrede","-n","hitap","Schreiben Sie auch eine Anrede und einen Gruß.","n","Bir hitap ve bir selam da yazın."],
["der","Anruf","-e","telefon araması","Sie bekommt viele Anrufe auf ihrem Handy.","n","Cep telefonuna çok arama geliyor."],
["der","Anrufbeantworter","-","telesekreter","Wir sind im Moment nicht da. Sprechen Sie bitte auf den Anrufbeantworter.","n","Şu anda evde değiliz. Lütfen telesekretere mesaj bırakın."],
["die","Ansage","-n","anons","Hören Sie die Ansagen.","n","Duyuruları dinleyin."],
["der","Anschluss","¨-e","aktarma; bağlantı","In Mannheim haben Sie Anschluss nach Saarbrücken.","n","Mannheim'da Saarbrücken'e aktarmanız var."],
["","an sein","","açık olmak","Heute Nacht war das Licht an.","x","Dün gece ışık açıktı."],
["","antworten","","cevap vermek","Er antwortet nicht.","v","Cevap vermiyor."],
["die","Antwort","-en","cevap","Er gibt leider keine Antwort.","n","Maalesef cevap vermiyor."],
["die","Anzeige","-n","ilan","Ich habe Ihre Anzeige in der Zeitung gelesen.","n","Gazetedeki ilanınızı okudum."],
["","anziehen","","giymek","Ich muss mich noch anziehen.","v","Hala giyinmem gerekiyor."],
["das","Apartment","-s","daire","Wir haben ein Apartment gemietet.","n","Bir daire kiraladık."],
["der","Appetit","","iştah","Guten Appetit!","n","Afiyet olsun!"],
["","arbeitslos","","işsiz","Es gibt bei uns viele Leute, die schon lange arbeitslos sind.","a","Bizde uzun süredir işsiz olan birçok insan var."],
["der","Arbeitsplatz","¨-e","işyeri","An meinem Arbeitsplatz fehlt ein Drucker.","n","İş yerimde yazıcı yok."],
["der","Arm","-e","kol","Mein Arm tut weh.","n","Kolum ağrıyor."],
["","auch","","de/da; ayrıca","Ich bin auch Spanier.","x","Ben de İspanyolum."],
["","auf","","üzerinde; -de/-da","Die Kinder spielen auf der Straße.","x","Çocuklar sokakta oynuyorlar."],
["die","Aufgabe","-n","görev","Das ist eine schwere Aufgabe.","n","Bu zor bir görev."],
["","aufhören","","bitmek; bırakmak","Der Kurs hört in einer Woche auf.","v","Kurs bir hafta sonra bitiyor."],
["","auf sein","","açık olmak","Du brauchst den Schlüssel nicht. Die Wohnung ist auf.","x","Anahtara ihtiyacın yok. Daire açık."],
["der","Aufzug","¨-e","asansör","In diesem Haus gibt es keinen Aufzug.","n","Bu evde asansör yok."],
["","aus","","-den/-dan; dışarı","Er kommt aus Brasilien.","x","Brezilya'dan geliyor."],
["der","Ausflug","¨-e","gezi","Morgen machen wir einen Ausflug nach Heidelberg.","n","Yarın Heidelberg'e bir geziye çıkıyoruz."],
["","ausfüllen","","doldurmak","Füllen Sie bitte dieses Formular aus.","v","Lütfen formu doldurun."],
["der","Ausgang","¨-e","çıkış","Wo ist der Ausgang?","n","Çıkış nerede?"],
["die","Auskunft","¨-e","bilgi; danışma","Können Sie mir eine Auskunft geben?","n","Bana bilgi verebilir misiniz?"],
["das","Ausland","","yurt dışı","Fahren Sie ins Ausland?","n","Yurt dışına mı gidiyorsun?"],
["der","Ausländer","-","yabancı","Sind Sie Ausländerin?","n","Yabancı mısınız?"],
["","ausländisch","","yabancı","Leider habe ich nur ausländisches Geld.","a","Maalesef sadece yabancı param var."],
["","ausmachen","","kapatmak; kararlaştırmak","Mach bitte das Licht aus!","v","Lütfen ışıkları kapatın!"],
["die","Aussage","-n","beyan","Ist die Aussage richtig oder falsch?","n","İfade doğru mu, yanlış mı?"],
["","aussehen","","görünmek","Das sieht schön aus.","v","Güzel görünüyor."],
["","aus sein","","kapalı olmak","Das Licht ist aus.","x","Işık kapalı."],
["","aussteigen","","inmek (araçtan)","Wo muss ich aussteigen?","v","Nerede inmem gerekiyor?"],
["","ausziehen","","soyunmak; taşınmak","Zieh die Schuhe aus, bitte!","v","Ayakkabılarınızı çıkarın lütfen!"],
["die","Autobahn","-en","otoyol","Wo geht's hier bitte zur Autobahn?","n","Otoyola nereden gidiliyor acaba?"],
["der","Automat","-en","otomat","Die Fahrkarten gibt es nur am Automaten.","n","Biletler yalnızca makinelerden alınabilir."],
["","automatisch","","otomatik","Du musst nichts machen. Das geht automatisch.","a","Hiçbir şey yapmanıza gerek yok. Bu otomatik olarak gerçekleşir."],
["das","Baby","-s","bebek","Mein Kind ist noch ein Baby.","n","Çocuğum henüz bebek."],
["das","Bad","¨-er","banyo","Wir haben kein großes Bad.","n","Büyük bir banyomuz yok."],
["","baden","","banyo yapmak","Ich bade nicht so gern, ich dusche lieber.","v","Banyo yapmayı pek sevmiyorum, duş almayı tercih ediyorum."],
["die","Bahn","-en","tren; demiryolu","Wir fahren lieber mit der Bahn.","n","Biz trene binmeyi tercih ediyoruz."],
["der","Bahnsteig","-e","peron","Auf welchem Bahnsteig fährt der Zug?","n","Tren hangi perondan kalkıyor?"],
["","bald","","yakında","Ich komme bald.","x","Yakında geliyorum."],
["der","Balkon","-e","balkon","Die Wohnung hat auch einen kleinen Balkon.","n","Dairede ayrıca küçük bir balkon bulunmaktadır."],
["die","Banane","-n","muz","Drei Bananen, bitte!","n","Üç muz lütfen!"],
["","bar","","nakit","Muss ich bar zahlen oder geht's auch mit Karte?","a","Nakit mi ödemem gerekiyor, yoksa kartla da olur mu?"],
["der","Bauch","¨-e","karın","Seit gestern tut mir der Bauch weh.","n","Dünden beri karnım ağrıyor."],
["der","Beamte","-n","memur","Fragen Sie die Beamtin an Schalter acht!","n","Sekizinci kontuardaki memura sorun!"],
["","bedeuten","","anlamına gelmek","Was bedeutet das Wort?","v","Kelime ne anlama geliyor?"],
["","beginnen","","başlamak","Das Spiel beginnt um 15.30 Uhr.","v","Maç saat 15.30'da başlıyor."],
["","bei","","-de/-da; yanında","Offenbach liegt bei Frankfurt.","x","Offenbach Frankfurt'a yakındır."],
["","beide","","ikisi de","Beide Eltern arbeiten.","x","Her iki ebeveyn de çalışıyor."],
["das","Bein","-e","bacak","Mein rechtes Bein tut weh.","n","Sağ bacağım ağrıyor."],
["das","Beispiel","-e","örnek","Kannst du mir ein Beispiel sagen?","n","Bana bir örnek verebilir misin?"],
["","zum Beispiel/z. B.","","örneğin","Viele meiner Verwandten, z. B. meine beiden Brüder, wohnen in Berlin.","x","Akrabalarımın çoğu, örneğin iki erkek kardeşim, Berlin'de yaşıyor."],
["","bekannt","","tanınmış, bilinen","Picasso ist sehr bekannt.","a","Picasso çok tanınmış."],
["der","Bekannte","-n","tanıdık","Ein Bekannter von mir heißt Klaus.","n","Bir tanıdığımın adı Klaus."],
["","bekommen","","almak","Haben Sie meinen Brief bekommen?","v","Mektubumu aldın mı?"],
["","benutzen","","kullanmak","Die Aufzüge bitte nicht benutzen!","v","Lütfen asansörleri kullanmayın!"],
["der","Beruf","-e","meslek","Was sind Sie von Beruf?","n","Mesleğiniz nedir?"],
["","besetzt","","meşgul, dolu","Die Nummer ist immer besetzt.","a","Numara sürekli meşgul."],
["","besichtigen","","gezmek (bir yeri)","Ich möchte gern den Dom besichtigen.","v","Katedrali gezmek isterim."],
["","besser","","daha iyi","Es geht mir schon besser.","a","Şimdiden daha iyi hissediyorum."],
["","am besten","","en iyisi","Am besten treffen wir uns morgen.","x","En iyisi yarın buluşalım."],
["","bestellen","","sipariş vermek","Wir möchten bestellen, bitte.","v","Sipariş vermek istiyoruz, lütfen."],
["","besuchen","","ziyaret etmek","Darf ich dich besuchen?","v","Seni ziyaret edebilir miyim?"],
["das","Bier","-e","bira","Noch ein Bier bitte.","n","Bir bira daha lütfen."],
["die","Birne","-n","armut","Ein Kilo Birnen, bitte!","n","Bir kilo armut lütfen!"],
["","bis","","kadar","Ich fahre nur bis Stuttgart.","x","Sadece Stuttgart'a kadar gidiyorum."],
["","bisschen","","biraz","Ich spreche Englisch, Französisch und ein bisschen Deutsch.","x","İngilizce, Fransızca ve biraz Almanca konuşuyorum."],
["","bitte","","lütfen","Eine Tasse Kaffee, bitte!","x","Bir fincan kahve lütfen!"],
["","bitten","","rica etmek","Darf ich Sie um etwas bitten?","v","Sizden bir şey rica edebilir miyim?"],
["","bitter","","acı","Der Kaffee schmeckt bitter.","a","Kahve acı."],
["der","Bleistift","-e","kurşun kalem","Hast du einen Bleistift?","n","Kalemin var mı?"],
["der","Blick","-e","manzara; bakış","Von diesem Hotel hat man einen guten Blick auf den See.","n","Bu otelden göle güzel bir manzara var."],
["der","Bogen","¨","form kâğıdı","Schreiben Sie Ihre Lösungen bitte auf den Antwortbogen.","n","Lütfen cevaplarınızı cevap kağıdına yazınız."],
["","böse","","kızgın; kötü","Sie ist böse auf mich.","a","Bana kızgın."],
["","breit","","geniş","Wie breit ist der Schrank?","a","Dolap ne kadar geniş?"],
["die","Briefmarke","-n","posta pulu","Kaufst du bitte Briefmarken bei der Post.","n","Postaneden pul alır mısın lütfen?"],
["","bringen","","getirmek","Bringen Sie mir bitte noch einen Kaffee!","v","Bana bir kahve daha getirir misiniz lütfen?"],
["das","Brötchen","-","küçük ekmek","Möchtest du Brötchen zum Frühstück?","n","Kahvaltıda küçük ekmek ister misin?"],
["der","Buchstabe","-n","harf","Diesen Buchstaben gibt es in meiner Sprache nicht.","n","Bu harf benim dilimde yok."],
["","buchstabieren","","harf harf söylemek, hecelemek","Bitte buchstabieren Sie Ihren Namen.","v","Lütfen adınızı heceleyin."],
["die","Butter","","tereyağı","Für mich bitte ein Brötchen mit Butter und Käse.","n","Benim için tereyağlı ve peynirli bir küçük ekmek lütfen."],
["das","Café","-s","kafe","Sollen wir uns im Café treffen?","n","Kafede buluşalım mı?"],
["die","CD","-s","CD","Bring bitte deine Lieblings-CD mit.","n","Lütfen en sevdiğin CD'yi getir."],
["der","Chef","-s","şef; patron","Wir haben eine neue Chefin.","n","Yeni bir patronumuz var."],
["","circa/ca.","","yaklaşık","Von Mainz nach Frankfurt sind es circa fünfzig Kilometer.","x","Mainz'dan Frankfurt'a yaklaşık elli kilometre."],
["der","Computer","-","bilgisayar","Wann bekommst du deinen neuen Computer?","n","Yeni bilgisayarını ne zaman alıyorsun?"],
["","da","","orada","Da hinten ist er ja.","x","İşte orada, arkada."],
["die","Dame","-n","hanım, bayan","Damen (an der Toilette)","n","Bayanlar (tuvalette)"],
["","daneben","","yanında","Du kennst doch die Post. Daneben ist die Bank.","x","Postaneyi bilirsin. Yanında banka var."],
["","danken","","teşekkür etmek","Ich danke Ihnen für die Einladung.","v","Davetiniz için teşekkür ederim."],
["der","Dank","","teşekkür","Vielen Dank!","n","Teşekkür ederim!"],
["","danke","","teşekkür ederim","Soll ich Ihnen helfen? - Nein, danke!","x","Sana yardım etmemi ister misin? - Hayır, teşekkürler!"],
["","dann","","sonra; o zaman","Ich muss noch schnell zur Post, dann komme ich.","x","Hemen postaneye uğramam lazım, sonra geliyorum."],
["das","Datum","Daten","tarih","Bitte schreiben Sie noch das Datum auf das Formular.","n","Lütfen forma tarihi yazınız."],
["","dauern","","sürmek","Wie lange dauert der Film?","v","Film ne kadar sürüyor?"],
["","dein","","senin","Ist das dein Auto?","x","Bu senin araban mı?"],
["","denn","","çünkü","Ich kann nicht kommen, denn ich bin krank.","x","Hasta olduğum için gelemiyorum."],
["","der, die, das","","bu, şu (işaret)","Ich nehme das da.","x","Şunu alıyorum."],
["","dich","","seni","Die Blumen sind für dich.","x","Çiçekler senin için."],
["","dieser","","bu","Ich nehme lieber diesen Kuchen.","x","Bu keki almayı tercih ederim."],
["","dir","","sana","Gefallen dir die Blumen?","x","Çiçekleri beğendin mi?"],
["die","Disco","-s","disko","Heute Abend gehen wir in die Disco tanzen.","n","Bu gece diskoda dans etmeye gideceğiz."],
["der","Doktor","-en","doktor","Meine Tochter ist krank. Wir gehen zum Doktor.","n","Kızım hasta. Doktora gidiyoruz."],
["das","Doppelzimmer","-","çift kişilik oda","Wollen Sie ein Doppelzimmer oder ein Einzelzimmer?","n","Çift kişilik oda mı yoksa tek kişilik oda mı istiyorsunuz?"],
["das","Dorf","¨-er","köy","Meine Familie lebt in einem Dorf.","n","Ailem bir köyde yaşıyor."],
["","dort","","orada (dorthin: oraya)","Deine Tasche kannst du dorthin stellen.","x","Çantanı oraya koyabilirsin."],
["","draußen","","dışarıda","Wollen wir draußen sitzen?","x","Dışarıda oturmak ister miyiz?"],
["","drucken","","yazdırmak, basmak","Bitte drucke das Formular für mich.","v","Lütfen formu benim için yazdır."],
["der","Drucker","-","yazıcı","Mein Drucker ist kaputt.","n","Yazıcım bozuldu."],
["","drücken","","basmak","Drück hier, dann geht der Computer an.","v","Buraya bas, bilgisayar açılır."],
["","durch","","içinden, -den geçerek","Am besten gehen Sie durch die Breite Straße.","x","Breite Straße'den geçmek en iyisidir."],
["die","Durchsage","-n","duyuru","Ich habe die Durchsage nicht verstanden.","n","Anonsu anlamadım."],
["","dürfen","","izinli olmak, -ebilmek (izin)","Sie dürfen hier nicht rauchen.","v","Burada sigara içmenize izin verilmiyor."],
["der","Durst","","susuzluk","Hast du etwas zu trinken? Ich habe großen Durst.","n","İçecek bir şeyin var mı? Çok susadım."],
["","duschen","","duş almak","Ich bade nicht so gern, ich dusche lieber.","v","Banyo yapmayı pek sevmiyorum, duş almayı tercih ediyorum."],
["die","Dusche","-n","duş","Unsere Wohnung hat nur eine Dusche.","n","Dairemizde sadece duş var."],
["die","Ehefrau","-en","eş","Meine Ehefrau arbeitet in einer Schule.","n","Eşim bir okulda çalışıyor."],
["der","Ehemann","¨-er","koca","Mein Ehemann arbeitet bei der Bank.","n","Kocam bankada çalışıyor."],
["","eilig","","acil, aceleli","Hast du es eilig?","a","Acelen mi var?"],
["","ein, eine","","bir","Ich nehme ein Bier. Willst du auch eins?","x","Bir bira içeceğim. Sen de bir tane ister misin?"],
["","einfach","","kolay, basit","Die Prüfung ist ganz einfach.","a","Sınav çok kolay."],
["der","Eingang","¨-e","giriş","Der Eingang ist um die Ecke.","n","Giriş köşededir."],
["","einladen","","davet etmek","Darf ich Sie zu einem Kaffee einladen?","v","Sizi bir kahveye davet edebilir miyim?"],
["die","Einladung","-en","davet","Danke für die Einladung!","n","Davetiniz için teşekkürler!"],
["","einmal","","bir kez","Diese Prüfung mache ich nicht noch einmal.","x","Bir daha bu sınava girmeyeceğim."],
["","einsteigen","","binmek (araca)","Schnell, steig ein, der Zug fährt gleich.","v","Çabuk bin, tren birazdan kalkıyor."],
["der","Eintritt","","giriş ücreti","Der Preis für den Eintritt ist 5 Euro.","n","Giriş ücreti 5 Euro'dur."],
["das","Einzelzimmer","-","tek kişilik oda","Haben Sie noch ein Einzelzimmer?","n","Boş tek kişilik odanız var mı?"],
["die","Eltern","","anne baba, ebeveynler","Meine Eltern leben in Spanien.","n","Annem ve babam İspanya'da yaşıyor."],
["die","E-Mail","-s","e-posta","Ich habe Ihre E-Mail nicht bekommen.","n","E-postanızı almadım."],
["der","Empfänger","-","alıcı","Auf dem Brief steht dein Name, also bist du der Empfänger.","n","Mektupta senin adın yazıyor, yani alıcı sensin."],
["","empfehlen","","tavsiye etmek","Welchen Wein können Sie mir empfehlen?","v","Bana hangi şarabı önerirsiniz?"],
["","enden","","bitmek, sona ermek","Die Straße endet hier.","v","Yol burada bitiyor."],
["das","Ende","-n","son","Sie wohnt am Ende der Straße.","n","Sokağın sonunda yaşıyor."],
["","entschuldigen","","özür dilemek","Entschuldigen Sie bitte!","v","Affedersiniz!"],
["die","Entschuldigung","-en","özür; affedersiniz","Entschuldigung! – Bitte.","n","Affedersiniz! – Rica ederim."],
["","er","","o","Er heißt Ali.","x","Adı Ali'dir."],
["das","Ergebnis","-se","sonuç","Das Ergebnis des Tests bekommen Sie in zwei Wochen.","n","Testin sonucunu iki hafta içinde alacaksınız."],
["","erklären","","açıklamak","Kannst du mir das erklären?","v","Bunu bana açıklayabilir misin?"],
["","erlauben","","izin vermek","Rauchen ist hier nicht erlaubt.","v","Burada sigara içmek yasaktır."],
["der","Erwachsene","-n","yetişkin","Dieser Film ist nur für Erwachsene.","n","Bu film yalnızca yetişkinler içindir."],
["","erzählen","","anlatmak","Wir müssen euch etwas erzählen!","v","Size bir şey anlatmamız lazım!"],
["","es","","o","Es regnet.","x","Yağmur yağıyor."],
["","euer","","sizin","Euer Kurs beginnt heute.","x","Kursunuz bugün başlıyor."],
["der","Fahrer","-","sürücü","Bitte nicht mit dem Fahrer sprechen!","n","Lütfen sürücüyle konuşmayın!"],
["","falsch","","yanlış","Das ist falsch.","a","Bu yanlış."],
["der","Familienname","-n","soyadı","Meine Familiennamen sind García González.","n","Soyadlarım García González."],
["der","Familienstand","","medeni durum","Bei „Familienstand“ musst du „ledig“ ankreuzen.","n","“Medeni durum” altında “bekar” seçeneğini işaretlemeniz gerekir."],
["das","Fax","-e","faks","Schicken Sie uns einfach ein Fax!","n","Bize bir faks göndermeniz yeterli!"],
["der","Feiertag","-e","bayram, resmî tatil","Morgen ist ein Feiertag. Die Geschäfte sind geschlossen.","n","Yarın resmî tatil. Dükkânlar kapalı."],
["","feiern","","kutlamak","Wir feiern heute meinen Geburtstag.","v","Bugün doğum günümü kutluyoruz."],
["","fehlen","","eksik olmak; (derse/işe) gelmemek","Herr Müller ist nicht da, er fehlt schon seit drei Tagen.","v","Bay Müller burada değil, üç gündür gelmiyor."],
["","fernsehen","","televizyon izlemek","Wollen wir heute Abend mal fernsehen?","v","Bu gece televizyon izleyelim mi?"],
["","fertig","","hazır; bitmiş","Bist du fertig?","a","Hazır mısın?"],
["das","Feuer","","ateş; yangın","Haben Sie Feuer?","n","Ateşiniz var mı?"],
["das","Fieber","","ateş (hastalık)","Mein Mann hat noch immer Fieber.","n","Kocamın hâlâ ateşi var."],
["","finden","","bulmak","Wir müssen den Schlüssel finden.","v","Anahtarı bulmalıyız."],
["die","Firma","Firmen","şirket","Er arbeitet jetzt bei einer anderen Firma.","n","Şu anda başka bir şirkette çalışıyor."],
["der","Fisch","-e","balık","Ich esse gern Fisch. Fleisch mag ich nicht.","n","Balık yemeyi severim. Eti sevmiyorum."],
["","fliegen","","uçmak","Ich fliege nicht gern. Deshalb fahre ich mit dem Zug.","v","Uçmayı sevmiyorum. Bu yüzden trene biniyorum."],
["","abfliegen","","(uçakla) kalkmak","Wann fliegst du ab?","v","Ne zaman uçuyorsun?"],
["der","Abflug","¨-e","kalkış (uçak)","Der Abflug ist um 11.20 Uhr.","n","Kalkış saat 11.20'de."],
["das","Flugzeug","-e","uçak","Das Flugzeug aus Berlin kommt heute später an.","n","Berlin'den gelen uçak bugün daha geç iniyor."],
["das","Foto","-s","fotoğraf","Darf ich ein Foto machen?","n","Fotoğraf çekebilir miyim?"],
["die","Frau","-en","kadın; hanım","Das ist Frau Becker.","n","Bu Bayan Becker."],
["","frei","","boş; serbest; ücretsiz","Ist der Platz noch frei?","a","Yer hâlâ müsait mi?"],
["die","Freizeit","","boş zaman","In meiner Freizeit spiele ich oft Fußball.","n","Boş zamanlarımda sıklıkla futbol oynarım."],
["","fremd","","yabancı","Das weiß ich nicht; ich bin fremd hier.","a","Bunu bilmiyorum, buranın yabancısıyım."],
["","sich freuen","","sevinmek; (auf) dört gözle beklemek","Ich freue mich auf den Urlaub.","v","Tatili sabırsızlıkla bekliyorum."],
["","früher","","eskiden; daha erken","Früher waren wir oft zusammen im Kino.","x","Eskiden sık sık birlikte sinemaya giderdik."],
["","frühstücken","","kahvaltı yapmak","Am Sonntag frühstücke ich gern im Bett.","v","Pazar günleri yatakta kahvaltı yapmayı severim."],
["die","Führung","-en","rehberli tur","Die Führung durch das Haus beginnt in 3 Minuten.","n","Binada rehberli tur 3 dakika sonra başlıyor."],
["","für","","için","Das ist für Sie.","x","Bu sizin için."],
["der","Fuß","¨-e","ayak","Der linke Fuß tut mir weh.","n","Sol ayağım ağrıyor."],
["der","Fußball","","futbol","Spielt ihr gerne Fußball?","n","Futbol oynamayı sever misiniz?"],
["","geben","","vermek","Kannst du mir bitte deinen Kugelschreiber geben?","v","Bana kalemini verir misin lütfen?"],
["","geboren","","doğmuş","Ich bin in Zagreb geboren.","a","Zagreb'de doğdum."],
["das","Geburtsjahr","-e","doğum yılı","Das Geburtsjahr Ihres Sohnes, bitte?","n","Oğlunuzun doğum yılı lütfen?"],
["der","Geburtsort","-e","doğum yeri","Bitte schreiben Sie Ihren Geburtsort auf das Formular.","n","Lütfen forma doğum yerinizi yazınız."],
["","gefallen","","hoşuna gitmek, beğenmek","Das gefällt mir.","v","Bu hoşuma gidiyor."],
["","gegen","","-e karşı; -e doğru; (saat) civarı","Fahr nicht gegen den Baum!","x","Ağaca çarpma!"],
["","gehören","","ait olmak","Wem gehört das?","v","Bu kime ait?"],
["das","Gepäck","","bagaj","Wollen Sie Ihr Gepäck mitnehmen?","n","Bagajınızı yanınıza almak ister misiniz?"],
["","gerade","","şu anda, tam; düz","Da kommt er ja gerade.","x","İşte tam şimdi geliyor."],
["","geradeaus","","dümdüz ileri","Gehen Sie immer geradeaus!","x","Hep dümdüz gidin!"],
["","gern(e)","","seve seve, memnuniyetle","Ich gehe gerne einkaufen.","x","Alışverişe gitmeyi severim."],
["das","Geschäft","-e","dükkân, mağaza; iş","Die Geschäfte schließen um 18.30 Uhr.","n","Dükkânlar 18.30'da kapanıyor."],
["die","Geschwister","","kardeşler","Ich habe leider keine Geschwister.","n","Ne yazık ki hiç kardeşim yok."],
["das","Gespräch","-e","konuşma","Das Gespräch mit Frau Kunz ist um 14 Uhr.","n","Bayan Kunz ile görüşme saat 14'te."],
["","gestorben","","ölmüş, vefat etmiş","Meine Frau ist gestern gestorben.","a","Eşim dün vefat etti."],
["das","Getränk","-e","içecek","Mein Lieblingsgetränk ist Tomatensaft.","n","En sevdiğim içecek domates suyudur."],
["das","Gewicht","-e","ağırlık","Bei „Gewicht“ schreibst du: 62 Kilo.","n","“Ağırlık” kısmına 62 kilo yazıyorsun."],
["","gewinnen","","kazanmak","Wer gewinnt das Spiel?","v","Maçı kim kazanacak?"],
["","glauben","","inanmak","Sie können mir glauben, es ist so.","v","Bana inanabilirsiniz, durum böyle."],
["","gleich","","aynı; hemen","Das ist mir gleich.","x","Umurumda değil."],
["das","Gleis","-e","peron","Der ICE nach Berlin hält heute an Gleis 12.","n","Berlin'e giden ICE bugün 12. peronda duruyor."],
["das","Glück","","şans; mutluluk","Viel Glück!","n","Bol şans!"],
["","glücklich","","mutlu","Meine Kinder sind glücklich verheiratet.","a","Çocuklarım mutlu bir evlilik yaşıyor."],
["der","Glückwunsch","¨-e","tebrik","Herzlichen Glückwunsch zum Geburtstag.","n","Doğum günün kutlu olsun."],
["","gratulieren","","tebrik etmek","Ich gratuliere dir!","v","Seni tebrik ediyorum!"],
["","grillen","","ızgara yapmak, mangal yapmak","Heute grillen wir im Garten.","v","Bugün bahçede mangal yapıyoruz."],
["die","Größe","-n","beden; boy; büyüklük","Haben Sie das auch in Größe 40?","n","Bunun 40 bedeni de var mı?"],
["die","Großeltern","","büyükanne ve büyükbaba","Meine Großeltern leben in Japan.","n","Büyükannem ve büyükbabam Japonya'da yaşıyor."],
["die","Großmutter","¨","büyükanne","Meine Großmutter heißt Eva.","n","Büyükannemin adı Eva."],
["der","Großvater","¨","büyükbaba","Mein Großvater ist schon 80.","n","Dedem 80 yaşında."],
["die","Gruppe","-n","grup","Die erste Gruppe beginnt um 16 Uhr.","n","İlk grup saat 16.00'da başlıyor."],
["der","Gruß","¨-e","selam","Viele Grüße an Ihre Frau.","n","Eşinize çok selamlar."],
["","gültig","","geçerli","Der Pass ist nicht mehr gültig.","a","Pasaport artık geçerli değil."],
["","günstig","","uygun (fiyatlı)","Dort gibt es günstige Angebote.","a","Orada uygun fiyatlı teklifler var."],
["","gut","","iyi","Das finde ich gut.","a","Bence bu iyi."],
["","haben","","sahip olmak","Ich habe ein neues Auto.","v","Yeni bir arabam var."],
["das","Hähnchen","-","tavuk","Ein Hähnchen mit Pommes bitte!","n","Bir tavuk ve patates kızartması lütfen!"],
["die","Halbpension","","yarım pansiyon","Möchten Sie Vollpension oder Halbpension?","n","Tam pansiyon mu yoksa yarım pansiyon mu tercih edersiniz?"],
["die","Halle","-n","salon","Wir treffen uns in Halle B.","n","B salonunda buluşuyoruz."],
["","hallo","","merhaba","Hallo Inge! Wie geht's?","x","Merhaba Inge! Nasılsın?"],
["","halten","","durmak; tutmak","Dieser Zug hält nicht in Rüdesheim.","v","Bu tren Rüdesheim'da durmuyor."],
["die","Haltestelle","-n","durak","An der nächsten Haltestelle müssen Sie aussteigen.","n","Bir sonraki durakta inmeniz gerekiyor."],
["die","Hausaufgabe","-n","ödev","Kannst du mir bei den Hausaufgaben helfen?","n","Ödevimde bana yardım edebilir misin?"],
["die","Hausfrau","-en","ev hanımı","Die Hausfrau kocht heute das Abendessen.","n","Ev hanımı bugün akşam yemeğini pişiriyor."],
["der","Hausmann","¨-er","ev erkeği","Der Hausmann wäscht, kocht und kauft ein.","n","Ev erkeği çamaşır yıkar, yemek yapar ve alışveriş yapar."],
["die","Heimat","","memleket; vatan","Ich komme aus der Schweiz. Das ist meine Heimat.","n","İsviçre'den geliyorum. Orası benim memleketim."],
["","heiraten","","evlenmek","Meine Schwester heiratet einen Japaner.","v","Kız kardeşim Japon bir adamla evleniyor."],
["","heißen","","adı … olmak","Ich heiße Charlotte Meier.","v","Adım Charlotte Meier."],
["","hell","","aydınlık; açık (renk)","Im Sommer ist es bis 21 Uhr hell.","a","Yaz aylarında hava akşam 9'a kadar aydınlıktır."],
["der","Herr","-en","bay; bey","Guten Tag, Herr Sommer!","n","İyi günler Bay Sommer!"],
["","herzlich","","içten, candan","Herzlichen Glückwunsch!","a","Tebrikler!"],
["","hier","","burada","Hier ist 06131-553221, Pamela Linke.","x","Ben 06131-553221, Pamela Linke."],
["die","Hilfe","","yardım","Hilfe! Bitte helfen Sie mir!","n","İmdat! Lütfen bana yardım edin!"],
["","hinten","","arkada","Die Tür zum Aussteigen ist hinten.","x","İniş kapısı arkada."],
["das","Hobby","-s","hobi","Meine Hobbys sind Wandern und Schwimmen.","n","Hobilerim yürüyüş yapmak ve yüzmek."],
["","hoch","","yüksek","Der Mount Everest ist 8.880 Meter hoch.","a","Everest Dağı 8.880 metre yüksekliğindedir."],
["die","Hochzeit","-en","düğün","Zu dieser Hochzeit kommen mehr als fünfzig Gäste.","n","Bu düğüne elliden fazla misafir geliyor."],
["","holen","","(gidip) getirmek, almak","Ich hole zwei Flaschen Wasser aus der Küche.","v","Mutfaktan iki şişe su getiriyorum."],
["","hören","","duymak","Hör mal! Was ist das?","v","Dinle! Bu ne?"],
["der","Hunger","","açlık","Ich habe Hunger! Wann ist das Essen fertig?","n","Açım! Yemek ne zaman hazır olur?"],
["","ich","","ben","Ich heiße Veronika.","x","Benim adım Veronika."],
["","ihr/ihm/ihn","","ona / ona / onu","Gib ihr/ihm bitte das Buch.","x","Lütfen ona kitabı verin."],
["","in","","içinde; -de/-da","Ich wohne in Wiesbaden.","x","Wiesbaden'de yaşıyorum."],
["die","Information","-en","bilgi; danışma","Wenn Sie Fragen haben, gehen Sie zur Information.","n","Sorunuz varsa danışmaya gidin."],
["","international","","uluslararası","Unser Deutschkurs ist international: Silvana kommt aus Italien, Ahmed aus der Türkei.","a","Almanca kursumuz uluslararası: Silvana İtalya'dan, Ahmed Türkiye'den geliyor."],
["das","Internet","","internet","Das findest du im Internet.","n","Bunu internette bulabilirsin."],
["","ja","","evet","Sind Sie Herr Watanabe? – Ja.","x","Siz Bay Watanabe misiniz? - Evet."],
["","jeder","","her","Blumen kannst du in jedem Bahnhof kaufen.","x","Çiçekleri her tren istasyonunda alabilirsin."],
["","jetzt","","şimdi","Jetzt machen wir eine Pause.","x","Şimdi biraz ara verelim."],
["der","Job","-s","iş","Jenny hat einen neuen Job bei der Post.","n","Jenny'nin postanede yeni bir işi var."],
["der","Jugendliche","-n","genç (ergen)","Viele Jugendliche kaufen gern ein.","n","Birçok genç alışveriş yapmayı sever."],
["","jung","","genç","Claudia ist 21. – Was? Noch so jung?","a","Claudia 21 yaşında. – Ne? Daha o kadar genç mi?"],
["der","Junge","-n","oğlan","Ich habe zwei Kinder. Einen Jungen und ein Mädchen.","n","İki çocuğum var. Bir oğlan ve bir kız."],
["","kaputt","","bozuk; kırık","Das Glas war teuer. Es geht sehr leicht kaputt.","a","Bardak pahalıydı. Çok kolay kırılıyor."],
["die","Karte","-n","kart; bilet; harita","Ich schreibe meinen Bekannten eine Karte aus dem Urlaub.","n","Tanıdıklarıma tatilden bir kart yazıyorum."],
["die","Kreditkarte","-n","kredi kartı","Kann ich auch mit Kreditkarte bezahlen?","n","Kredi kartıyla da ödeyebilir miyim?"],
["","kein","","hiç … yok, hiçbir","Es gibt keine Eintrittskarten mehr.","x","Artık hiç bilet kalmadı."],
["","kennen","","tanımak, bilmek","Kennen Sie diese Frau? – Nein, leider nicht.","v","Bu kadını tanıyor musunuz? – Hayır, maalesef."],
["","kennenlernen","","tanımak","Wir sind neu hier. Wir möchten Sie kennenlernen.","v","Burada yeniyiz. Sizi tanımak isteriz."],
["der","Kindergarten","¨","anaokulu","Die kleine Laura geht schon in den Kindergarten.","n","Küçük Laura zaten anaokuluna gidiyor."],
["der","Kiosk","-e","büfe","Am Kiosk bekommen Sie Getränke, Zigaretten und Zeitungen.","n","Büfeden içecek, sigara ve gazete alabilirsiniz."],
["","klar","","açık, anlaşılır; tabii","Kommst du mit? – Klar!","a","Benimle geliyor musun? - Elbette!"],
["die","Klasse","-n","sınıf","In unserer Klasse sind fünfundzwanzig Schüler.","n","Sınıfımızda yirmi beş öğrenci var."],
["die","Kleidung","","giyim; kıyafet","Wo finde ich Kleidung? – Jacken im ersten, Jeans im zweiten Stock.","n","Kıyafetleri nerede bulabilirim? – Ceketler birinci, kot pantolonlar ikinci katta."],
["der","Kollege","-n","iş arkadaşı","Wie heißt die neue Kollegin?","n","Yeni iş arkadaşının adı ne?"],
["","kommen","","gelmek","Woher kommen Sie? – Aus Frankreich.","v","Nerelisiniz? – Fransa'dan."],
["","können","","-ebilmek; bilmek (dil)","Ich kann Deutsch und Russisch.","v","Almanca ve Rusça konuşabiliyorum."],
["das","Konto","Konten","hesap","Das Geld überweisen wir am ersten März auf Ihr Konto.","n","Parayı 1 Mart'ta hesabınıza havale ediyoruz."],
["","kosten","","(fiyatı) tutmak","Wie viel kostet das? – 10 Euro.","v","Bu ne kadar? – 10 euro."],
["","kriegen","","almak","Ich kriege 15 Euro in der Stunde für meine Arbeit.","v","Çalışmam karşılığında saat başına 15 euro alıyorum."],
["der","Kugelschreiber","-","tükenmez kalem","Hast du einen Kugelschreiber für mich?","n","Bana verebileceğin bir tükenmez kalemin var mı?"],
["","kulturell","","kültürel","Ich bin kulturell interessiert. Ich gehe oft ins Museum.","a","Kültüre ilgim var. Sık sık müzeye giderim."],
["","sich kümmern","","ilgilenmek, bakmak (um)","Jede Mutter kümmert sich um ihre kleinen Kinder.","v","Her anne küçük çocuklarına bakar."],
["der","Kunde","-n","müşteri","Einen Moment, bitte. Ich habe eine Kundin.","n","Bir dakika lütfen. Bir müşterim var."],
["der","Kurs","-e","kurs","Der Deutschkurs geht bis zum Sommer.","n","Almanca kursu yaza kadar devam edecek."],
["","kurz","","kısa","Ricardo hat kurzes Haar.","a","Ricardo'nun saçları kısa."],
["","lachen","","gülmek","Die Kinder lachen viel.","v","Çocuklar çok gülüyorlar."],
["der","Laden","¨","dükkan","Im Buchladen können Sie Bücher kaufen.","n","Kitapçıda kitap alabilirsiniz."],
["","lang","","uzun","Die Jeans ist zu lang.","a","Kot pantolon çok uzun."],
["","lange","","uzun süre","Wie lange fährt der Zug von Hamburg nach Berlin?","x","Tren Hamburg'dan Berlin'e ne kadar sürüyor?"],
["","langsam","","yavaş","Könnten Sie bitte etwas langsamer sprechen?","a","Lütfen biraz daha yavaş konuşabilir misiniz?"],
["","laufen","","yürümek; koşmak","Ich möchte nicht Auto fahren, ich möchte laufen.","v","Araba kullanmak istemiyorum, yürümek istiyorum."],
["","laut","","yüksek sesli, gürültülü","Nicht so laut! Das Baby schläft.","a","Bu kadar gürültü yapmayın! Bebek uyuyor."],
["","leben","","yaşamak","Sie lebt bei ihrer Schwester.","v","Kız kardeşiyle birlikte yaşıyor."],
["die","Lebensmittel","","gıda, yiyecekler","Wir kaufen die Lebensmittel im Supermarkt.","n","Yiyecekleri süpermarketten alıyoruz."],
["","ledig","","bekar","Sind Sie verheiratet? – Nein. Ledig.","a","Evli misiniz? – Hayır. Bekârım."],
["","legen","","koymak, yatırmak","Legen Sie das Buch auf den Tisch.","v","Kitabı masaya koyun."],
["","leise","","sessiz, alçak sesle","Seid leise. Die anderen schlafen schon.","a","Sessiz olun. Diğerleri uyuyor."],
["","letzte","","son","Morgen ist der letzte Kurstag.","a","Yarın kursun son günü."],
["die","Leute","","insanlar","In der Disko sind viele Leute.","n","Diskoda bir sürü insan var."],
["","lieb","","sevgili; sevimli","Liebe Susanne, lieber Hans, vielen Dank für eure Karte.","a","Sevgili Susanne, sevgili Hans, kartınız için çok teşekkürler."],
["","lieben","","sevmek","Ich liebe dich!","v","Seni seviyorum!"],
["","lieber","","tercihen, daha çok","Sie fährt lieber mit der Bahn.","x","Trene binmeyi tercih ediyor."],
["","Lieblings-","","en sevilen … (ön ek)","Mein Lieblingsfilm ist „Schwarze Augen“.","x","En sevdiğim film “Kara Gözler”."],
["","liegen","","yatmak; bulunmak","Um neun Uhr liegt Judith noch im Bett.","v","Judith saat dokuzda hâlâ yatakta."],
["","links","","solda, sola","Gehen Sie die nächste Straße links.","x","Bir sonraki sokaktan sola dönün."],
["der","Lkw","-s","kamyon","Der Lkw ist sehr groß.","n","Kamyon çok büyük."],
["das","Lokal","-e","lokanta","In unserer Straße gibt es ein neues Lokal.","n","Sokağımızda yeni bir lokanta var."],
["die","Lösung","-en","çözüm","Die Lösung ist ganz einfach.","n","Çözüm çok basit."],
["","lustig","","komik","Frau Mertens ist lustig. Sie lacht immer.","a","Bayan Mertens komiktir. Her zaman gülüyor."],
["","machen","","yapmak","Was machst du heute Abend?","v","Bu akşam ne yapıyorsun?"],
["","man","","insan, biri (genel özne)","Hier darf man nicht rauchen.","x","Burada sigara içilmez."],
["der","Mann","¨-er","adam; koca","Mein Mann arbeitet bei der Polizei.","n","Kocam polis teşkilatında çalışıyor."],
["","männlich","","erkek","Kreuzen Sie bitte an: „weiblich“ oder „männlich“.","a","Lütfen işaretleyin: “kadın” veya “erkek”."],
["die","Maschine","-n","makine","Die Waschmaschine ist günstig.","n","Çamaşır makinesi ucuz."],
["","mehr","","daha fazla","Dieses Auto kostet 1.000 Euro mehr als das andere.","x","Bu arabanın fiyatı diğerinden 1000 euro daha fazla."],
["","mein","","benim","Mein Vater ist Arzt.","x","Babam doktordur."],
["","meiste","","çoğu, en çok","Die meisten Norddeutschen sind sehr groß.","a","Kuzey Almanların çoğu çok uzundur."],
["der","Mensch","-en","insan","Die Menschen sind hier anders als bei uns.","n","Buradaki insanlar bizden farklı."],
["","mieten","","kiralamak","Ich möchte ein Auto mieten.","v","Araba kiralamak istiyorum."],
["","mit","","ile","Trinken Sie den Kaffee mit Milch?","x","Kahveyi sütlü mü içersiniz?"],
["","mitbringen","","yanında getirmek","Ich gehe einkaufen. Soll ich dir was mitbringen?","v","Alışverişe gidiyorum. Sana bir şey getirmemi ister misin?"],
["","mitkommen","","birlikte gelmek","Ich gehe ins Kino. Kommst du mit?","v","Sinemaya gidiyorum. Benimle geliyor musun?"],
["","mitmachen","","katılmak","Warum macht ihr nicht mit?","v","Neden siz de katılmıyorsunuz?"],
["","mitnehmen","","yanına almak; götürmek","Nehmen wir meine Schwester ins Kino mit?","v","Kardeşimi sinemaya götürelim mi?"],
["die","Mitte","","orta","Der Lehrer steht in der Mitte des Klassenzimmers.","n","Öğretmen sınıfın ortasında durur."],
["die","Möbel","","mobilya","Sind die Möbel neu?","n","Mobilyalar yeni mi?"],
["","möchten","","istemek (kibar)","Was möchten Sie trinken?","v","Ne içmek istersiniz?"],
["","mögen","","sevmek, hoşlanmak","Magst du Kaffee oder Tee?","v","Kahve mi seversin, çay mı?"],
["","möglich","","mümkün","Mit dieser Fahrkarte ist die Fahrt ab 9 Uhr möglich.","a","Bu biletle sabah 9'dan itibaren seyahat edebilirsiniz."],
["der","Moment","-e","an; bir dakika","Moment mal bitte!","n","Bir dakika lütfen!"],
["der","Mund","¨-er","ağız","Öffnen Sie den Mund.","n","Ağzınızı açın."],
["","müssen","","zorunda olmak, -meli","Ich muss jeden Tag von 8 Uhr bis 18 Uhr arbeiten.","v","Her gün sabah 8'den akşam 6'ya kadar çalışmak zorundayım."],
["","nach","","-e/-a (yön); sonra","Ich gehe jetzt nach Hause.","x","Şimdi eve gidiyorum."],
["","nächste","","sonraki, gelecek","Sehen wir uns nächste Woche?","a","Gelecek hafta görüşecek miyiz?"],
["","nehmen","","almak","Heute gibt es Hähnchen. Das nehme ich.","v","Bugün tavuk var. Onu alıyorum."],
["","nein","","hayır","Fährst du auch nach München? – Nein, ich habe keine Zeit.","x","Sen de Münih'e gidiyor musun? – Hayır, vaktim yok."],
["","nicht","","değil","Das stimmt nicht.","x","Bu doğru değil."],
["","nichts","","hiçbir şey","Das macht nichts.","x","Bunun önemi yok."],
["","nie","","asla","Er kommt nie pünktlich.","x","Asla zamanında gelmez."],
["","noch","","hâlâ; daha","Vielleicht kommt er noch.","x","Belki gelir."],
["","normal","","normal","75 kg. Sein Gewicht ist normal.","a","75 kg. Kilosu normal."],
["die","Nummer","-n","numara","Sie haben Zimmer Nummer zwölf.","n","On iki numaralı odanız var."],
["","nur","","sadece","Ich möchte nur ein Glas Wasser.","x","Sadece bir bardak su istiyorum."],
["","oben","","yukarıda","Ich wohne oben.","x","Üst katta yaşıyorum."],
["","oder","","veya","Wann können Sie kommen – heute oder morgen?","x","Ne zaman gelebilirsiniz – bugün mü, yarın mı?"],
["","öffnen","","açmak","Ich öffne die Tür.","v","Kapıyı açıyorum."],
["","geöffnet","","açık","Der Laden ist samstags bis 16.00 Uhr geöffnet.","a","Mağaza cumartesi günleri saat 16.00'ya kadar açıktır."],
["","oft","","sık sık","Petra treffe ich oft.","x","Petra'yla sık sık buluşuyorum."],
["","ohne","","-sız/-siz, olmadan","Ohne Geld kann er nichts kaufen.","x","Para olmadan hiçbir şey satın alamaz."],
["das","Öl","-e","yağ","Den Salat machen wir ohne Öl.","n","Salatayı yağsız yapıyoruz."],
["die","Oma","-s","büyükanne","Meine Oma ist schon tot.","n","Büyükannem artık hayatta değil."],
["der","Opa","-s","dede","Mein Opa heißt Hans.","n","Büyükbabamın adı Hans'tır."],
["die","Ordnung","","düzen; (in Ordnung) tamam","Das ist in Ordnung.","n","Sorun değil."],
["der","Ort","-e","yer","Der Ort liegt am Meer.","n","Bu yer deniz kenarında."],
["das","Papier","-e","kağıt","Hier sind Papier und Bleistift.","n","İşte kağıt ve kalem."],
["die","Papiere","","belgeler; evrak","Haben Sie Ihre Papiere dabei?","n","Evraklarınız yanınızda mı?"],
["der","Partner","-","partner; ortak","Mein Partner wohnt in Berlin.","n","Partnerim Berlin'de yaşıyor."],
["die","Partnerin","-nen","partner (kadın); ortak","Sie ist meine Partnerin.","n","O benim ortağım."],
["die","Party","-s","parti","Heute Abend machen wir eine Party.","n","Bu gece bir parti veriyoruz."],
["die","Pause","-n","mola","Von 12.00 bis 12.30 Uhr haben wir Mittagspause.","n","12.00 ile 12.30 arası öğle aramız var."],
["der","Plan","¨-e","plan; harita","Ich kaufe mir einen Stadtplan.","n","Kendime bir şehir haritası alıyorum."],
["der","Platz","¨-e","yer","Tut mir leid, der Platz ist besetzt.","n","Üzgünüm, bu yer dolu."],
["die","Pommes frites","","patates kızartması","Die Kinder essen Hähnchen mit Pommes frites.","n","Çocuklar tavuk ve patates kızartması yerler."],
["die","Postleitzahl","-en","posta kodu","Wie ist Ihre Postleitzahl?","n","Posta kodunuz nedir?"],
["das","Praktikum","Praktika","staj","Ich mache ein Praktikum bei Siemens.","n","Siemens'te staj yapıyorum."],
["die","Praxis","Praxen","muayenehane","Die Praxis ist ab acht Uhr geöffnet.","n","Muayenehane saat sekizden itibaren açıktır."],
["der","Preis","-e","fiyat","Die Preise sind hoch.","n","Fiyatlar yüksek."],
["das","Problem","-e","sorun","Mein Problem ist die Sprache.","n","Benim sorunum dil."],
["der","Prospekt","-e","broşür","Bitte schicken Sie mir einen Prospekt von Ihrem Hotel.","n","Lütfen bana otelinizden bir broşür gönderin."],
["die","Prüfung","-en","sınav","Die Prüfung ist am Montag um 8.00 Uhr.","n","Sınav pazartesi günü saat 08.00'de."],
["","pünktlich","","zamanında","Der Bus fährt pünktlich um acht Uhr.","a","Otobüs tam saat sekizde kalkıyor."],
["","Rad fahren","","bisiklete binmek","Das Kind kann schon Rad fahren.","v","Çocuk zaten bisiklete binebiliyor."],
["","rauchen","","sigara içmek","Ich rauche nicht.","v","Sigara içmem."],
["der","Raum","¨-e","oda, salon","Der Unterricht ist in Raum 332.","n","Ders 332 numaralı salonda."],
["","rechts","","sağda, sağa","Die Schillerstraße ist hier rechts.","x","Schillerstrasse burada sağda."],
["","regnen","","yağmur yağmak","Heute regnet es.","v","Bugün yağmur yağıyor."],
["der","Reis","","pirinç","Ich esse gern Reis.","n","Pirinç yemeyi severim."],
["","reisen","","seyahat etmek","Ich reise gern.","v","Seyahat etmeyi severim."],
["das","Reisebüro","-s","seyahat acentesi","Mein Mann arbeitet im Reisebüro.","n","Kocam bir seyahat acentesinde çalışıyor."],
["der","Reiseführer","-","seyahat rehberi","Ich kaufe mir einen Reiseführer von Berlin.","n","Berlin seyahat rehberi satın alıyorum."],
["","reparieren","","tamir etmek","Er hat das Fahrrad repariert.","v","Bisikleti tamir etti."],
["die","Reparatur","-en","onarım","Die Reparatur ist sehr teuer.","n","Onarım çok pahalıdır."],
["das","Restaurant","-s","restoran","Wir essen heute in einem Restaurant.","n","Bugün bir restoranda yemek yiyoruz."],
["die","Rezeption","-en","resepsiyon","Fragen Sie bitte im Hotel an der Rezeption.","n","Lütfen otelin resepsiyonuna danışınız."],
["","richtig","","doğru","Habe ich das richtig verstanden?","a","Bunu doğru anladım mı?"],
["","riechen","","kokmak","Dieser Wein riecht gut.","v","Bu şarap güzel kokuyor."],
["","ruhig","","sakin, sessiz","Ich möchte ein ruhiges Zimmer.","a","Sessiz bir oda istiyorum."],
["der","Saft","¨-e","meyve suyu","Möchtest du einen Apfelsaft?","n","Elma suyu ister misin?"],
["","sagen","","demek","Sag mal, wie geht es dir denn?","v","Söyle bana, nasılsın?"],
["der","Salat","-e","salata","Wie schmeckt dir der Salat?","n","Salata nasıl, beğendin mi?"],
["das","Salz","","tuz","Herr Ober, kann ich bitte Salz haben?","n","Garson bey, biraz tuz alabilir miyim lütfen?"],
["der","Satz","¨-e","cümle","Dieser Satz ist sehr einfach.","n","Bu cümle çok basittir."],
["die","S-Bahn","-en","banliyö treni","Ich nehme lieber die S-Bahn.","n","S-Bahn'a binmeyi tercih ederim."],
["der","Schalter","-","gişe","Gehen Sie bitte zum Schalter drei!","n","Lütfen üç numaralı gişeye gidin!"],
["","scheinen","","parlamak (güneş); görünmek","Die Sonne scheint.","v","Güneş parlıyor."],
["","schicken","","göndermek","Bitte schicken Sie mir eine E-Mail.","v","Lütfen bana bir e-posta gönderin."],
["das","Schild","-er","tabela","Haben Sie nicht das Schild gesehen?","n","Tabelayı görmediniz mi?"],
["der","Schinken","-","jambon","Ich möchte gern ein Schinkenbrot.","n","Jambonlu sandviç istiyorum."],
["","schlecht","","kötü","Mir ist schlecht!","a","Midem bulanıyor!"],
["","schließen","","kapatmak","Bitte schließen Sie die Tür.","v","Lütfen kapıyı kapatın."],
["","geschlossen","","kapalı","Die Bank hat am Samstag geschlossen.","a","Banka cumartesi kapalı."],
["der","Schluss","","son; bitiş","Ich muss jetzt Schluss machen.","n","Artık bitirmem lazım."],
["","schmecken","","tadı … olmak, lezzetli gelmek","Schmeckt das gut?","v","Tadı güzel mi?"],
["","schon","","zaten; çoktan; bile","Ist das Essen schon fertig?","x","Yemek hazır oldu mu?"],
["","schön","","güzel","Schönen Urlaub!","a","Güzel bir tatil geçirin!"],
["der","Schüler","-","öğrenci","In meinem Kurs sind acht Schülerinnen und fünf Schüler.","n","Kursumda sekiz kız ve beş erkek öğrenci var."],
["","schwimmen","","yüzmek","Ich schwimme jeden Tag einen Kilometer.","v","Her gün bir kilometre yüzüyorum."],
["das","Schwimmbad","¨-er","yüzme havuzu","Kommst du mit ins Schwimmbad?","n","Yüzme havuzuna geliyor musun?"],
["der","See","-n","göl","Komm, wir fahren zum Starnberger See.","n","Hadi, Starnberg Gölü'ne gidelim."],
["","sehen","","görmek","Ich kann dich nicht sehen.","v","Seni göremiyorum."],
["die","Sehenswürdigkeit","-en","turistik yer","Die Sehenswürdigkeit ist sehr schön.","n","Bu turistik yer çok güzel."],
["","sehr","","çok","Danke sehr!","x","Çok teşekkür ederim!"],
["","sein","","olmak","Herr Müller ist in seinem Zimmer.","v","Bay Müller odasında."],
["","weg sein","","gitmiş olmak","Herr Meier ist schon weg.","x","Bay Meier çoktan gitti."],
["","zu sein","","kapalı olmak","Die Tür ist zu.","x","Kapı kapalı."],
["","seit","","-den beri","Ich wohne seit drei Jahren in Köln.","x","Üç yıldır Köln'de yaşıyorum."],
["","selbstständig","","serbest çalışan; bağımsız","Er ist selbstständig.","a","Kendi işini yapıyor."],
["","sich","","kendini (dönüşlü)","Sie müssen sich erst anmelden.","x","Önce kayıt olmanız gerekiyor."],
["","sie","","o (kadın); onlar","Wie heißt sie?","x","Onun adı ne?"],
["","sitzen","","oturmak","Wo sitzen Sie?","v","Nerede oturuyorsunuz?"],
["","so","","böyle","Sie müssen das so machen!","x","Bunu böyle yapmalısınız!"],
["das","Sofa","-s","kanepe","Das Sofa ist neu.","n","Kanepe yeni."],
["","sofort","","hemen","Bitte antworten Sie sofort.","x","Lütfen hemen cevap verin."],
["der","Sohn","¨-e","oğul","Das ist Hans, mein Sohn.","n","Bu Hans, oğlum."],
["","sollen","","-meli; -eyim mi","Soll ich kommen?","v","Geleyim mi?"],
["","spät","","geç","Es ist schon spät, ich muss gehen.","a","Geç oldu bile, gitmem lazım."],
["","später","","daha sonra","Das können wir später machen.","x","Bunu daha sonra yapabiliriz."],
["die","Speisekarte","-n","menü","Bringen Sie mir die Speisekarte, bitte.","n","Bana menüyü getirir misiniz lütfen?"],
["","spielen","","oynamak","Die Kinder spielen draußen.","v","Çocuklar dışarıda oynuyorlar."],
["der","Sport","","spor","Ich mache viel Sport.","n","Çok spor yapıyorum."],
["","stehen","","ayakta durmak; yazılı olmak","Ich glaube es nicht, aber es steht in der Zeitung.","v","İnanamıyorum ama gazetede yazıyor."],
["die","Stelle","-n","iş, pozisyon; yer","Ich habe eine neue Stelle.","n","Yeni bir işim var."],
["","stellen","","koymak","Stell die Tasche rechts in die Ecke!","v","Çantayı sağ köşeye koy!"],
["der","Stock","","kat","Unsere Wohnung liegt im ersten Stock.","n","Dairemiz birinci kattadır."],
["die","Straßenbahn","-en","tramvay","Wo fährt die Straßenbahn ab?","n","Tramvay nereden kalkıyor?"],
["","studieren","","üniversitede okumak","Ich studiere in Mainz.","v","Mainz'da okuyorum."],
["das","Studium","","üniversite eğitimi","Das Studium beginnt im Oktober.","n","Eğitim ekimde başlıyor."],
["der","Student","-en","üniversite öğrencisi","Ich bin Studentin.","n","Ben üniversite öğrencisiyim."],
["","suchen","","aramak","Suchst du etwas?","v","Bir şey mi arıyorsun?"],
["","tanzen","","dans etmek","Tanzen Sie gern?","v","Dans etmeyi sever misiniz?"],
["das","Taxi","-s","taksi","Es gibt heute keinen Bus mehr. Er fährt mit dem Taxi.","n","Bugün artık otobüs yok. Taksiyle gidiyor."],
["der","Teil","-e","kısım","Lies bitte auch den zweiten Teil.","n","Lütfen ikinci kısmı da oku."],
["","telefonieren","","telefonla konuşmak","Darf ich mal telefonieren?","v","Bir telefon edebilir miyim?"],
["das","Telefon","-e","telefon","Haben Sie Telefon?","n","Telefonunuz var mı?"],
["der","Test","-s","test","Der Test war einfach.","n","Test kolaydı."],
["der","Text","-e","metin","Lesen Sie bitte diesen Text.","n","Lütfen bu metni okuyun."],
["das","Thema","Themen","konu","Wir sprechen heute über das Thema „Essen und Trinken“.","n","Bugün “Yeme ve İçme” konusunu konuşuyoruz."],
["das","Ticket","-s","bilet","Wie viel kostet das Ticket?","n","Biletin fiyatı ne kadar?"],
["die","Toilette","-en","tuvalet","Wo ist die Toilette, bitte?","n","Tuvalet nerede lütfen?"],
["die","Tomate","-n","domates","Die Tomate ist noch grün.","n","Domates hâlâ yeşil."],
["","tot","","ölü","Sein Vater ist schon lange tot.","a","Babası uzun zaman önce öldü."],
["","treffen","","buluşmak; rastlamak","Ich treffe in der Stadt einen Kollegen.","v","Şehirde bir iş arkadaşımla buluşuyorum."],
["die","Treppe","-n","merdiven","Die Toilette? Die Treppe hoch und dann links.","n","Tuvalet mi? Merdivenden yukarı, sonra sola."],
["","tschüss","","hoşça kal","Junge Leute sagen meistens „tschüss!“ und nicht „Auf Wiedersehen!“.","x","Gençler genellikle “Auf Wiedersehen!” değil, “tschüss!” der."],
["","tun","","yapmak","Ich habe noch etwas zu tun.","v","Hala yapacak bir şeyim var."],
["","über","","üzerinden, karşıya; hakkında","Gehen Sie hier über die Straße.","x","Burada caddenin karşısına geçin."],
["","übernachten","","geceyi geçirmek, konaklamak","Du kannst bei mir übernachten.","v","Bende kalabilirsin."],
["","überweisen","","havale etmek","Sie können das Geld auch überweisen.","v","Parayı havale de edebilirsiniz."],
["","um","","saat …'de; etrafında","Er kommt um sieben Uhr.","x","Saat yedide geliyor."],
["","umziehen","","taşınmak","Nächsten Monat ziehen wir um.","v","Gelecek ay taşınıyoruz."],
["","und","","ve","Peter und Helmut sind meine Söhne.","x","Peter ve Helmut benim oğullarım."],
["","unser","","bizim","Das ist unsere Lehrerin.","x","Bu bizim öğretmenimiz."],
["","unten","","aşağıda","Er wohnt ganz unten im Haus.","x","Evin alt katında yaşıyor."],
["","unter","","altında","Unter uns wohnt eine Familie mit drei Kindern.","x","Altımızda üç çocuklu bir aile yaşıyor."],
["der","Unterricht","","ders","Wir haben Unterricht von 8.00 bis 12.00 Uhr.","n","Sabah 8'den öğlen 12'ye kadar dersimiz var."],
["","unterschreiben","","imzalamak","Wo muss ich unterschreiben?","v","Nereye imza atmam gerekiyor?"],
["die","Unterschrift","-en","imza","Hier fehlt noch Ihre Unterschrift.","n","Burada imzanız eksik."],
["","verboten","","yasak","Hier ist Rauchen verboten.","a","Burada sigara içmek yasaktır."],
["","verdienen","","kazanmak","Ich verdiene 1.500 Euro im Monat.","v","Ayda 1.500 euro kazanıyorum."],
["der","Verein","-e","dernek; kulüp","Es gibt einen neuen Sportverein in der Stadt.","n","Şehirde yeni bir spor kulübü var."],
["","verheiratet","","evli","Ich bin verheiratet und habe drei Kinder.","a","Evliyim ve üç çocuğum var."],
["","verkaufen","","satmak","Er verkauft sein altes Auto.","v","Eski arabasını satıyor."],
["der","Verkäufer","-","satıcı","Meine Mutter ist Verkäuferin im Kaufhaus.","n","Annem bir mağazada satış elemanı."],
["","vermieten","","kiraya vermek","Die Wohnung ist schon vermietet.","v","Daire çoktan kiralandı."],
["der","Vermieter","-","ev sahibi","Unser Vermieter heißt Huber. Er wohnt auch hier.","n","Ev sahibimizin adı Huber. O da burada yaşıyor."],
["der","Verwandte","-n","akraba","Peter besucht seine Verwandten in Polen.","n","Peter Polonya'daki akrabalarını ziyaret ediyor."],
["","viel","","çok","Hier regnet es viel.","a","Burada çok yağmur yağıyor."],
["","von","","-den/-dan; -in (aitlik)","Das Auto von Felix ist kaputt.","x","Felix'in arabası bozuldu."],
["","vor","","önce","Der Termin war vor einer Stunde.","x","Randevu bir saat önceydi."],
["der","Vorname","-n","ad","Ich heiße Müller, mein Vorname ist Eva.","n","Soyadım Müller, adım Eva."],
["die","Vorsicht","","dikkat","Vorsicht! Da kommt ein Auto.","n","Dikkat! Bir araba geliyor."],
["","sich vorstellen","","kendini tanıtmak; hayal etmek","Wir wollen uns kennenlernen. Können Sie sich bitte vorstellen?","v","Birbirimizi tanımak istiyoruz. Lütfen kendinizi tanıtır mısınız?"],
["die","Vorwahl","-en","alan kodu","Wie ist die Vorwahl von München?","n","Münih'in alan kodu nedir?"],
["","wandern","","doğa yürüyüşü yapmak","Wir wandern um den Chiemsee.","v","Chiemsee Gölü çevresinde yürüyüş yapıyoruz."],
["","wann","","ne zaman","Wann bist du fertig?","x","Ne zaman hazır olursun?"],
["","warten","","beklemek","Können Sie ein paar Minuten warten?","v","Birkaç dakika bekleyebilir misiniz?"],
["","warum","","neden","Warum kommt er nicht?","x","Neden gelmiyor?"],
["","was","","ne","Was ist das?","x","Bu nedir?"],
["","was für ein","","ne tür, nasıl bir","Was für eine Farbe möchten Sie?","x","Ne renk istersiniz?"],
["","waschen","","yıkamak","Wo kann ich mir die Hände waschen?","v","Ellerimi nerede yıkayabilirim?"],
["","weh tun","","acımak, ağrımak","Ich muss zum Arzt. Mein Bein tut weh.","v","Doktora gitmeliyim. Bacağım ağrıyor."],
["","weiblich","","kadın","Kreuzen Sie bitte an: „weiblich“ oder „männlich“.","a","Lütfen işaretleyin: “kadın” veya “erkek”."],
["der","Wein","-e","şarap","Nein danke, ich möchte keinen Wein.","n","Hayır teşekkürler, şarap istemiyorum."],
["","weit","","uzak","Zum Bahnhof ist es nicht weit.","a","İstasyon uzak değil."],
["","weiter","","daha ileri; devam","Der Bus fährt nicht weiter.","x","Otobüs daha ileri gitmiyor."],
["","welcher","","hangi","Welches Buch möchtest du?","x","Hangi kitabı istiyorsun?"],
["die","Welt","-en","dünya","Es gibt viele Probleme auf der Welt.","n","Dünyada birçok sorun var."],
["","wenig","","az","Ich habe leider nur wenig verstanden.","a","Ne yazık ki çok az şey anladım."],
["","wer","","kim","Wer ist das?","x","Kim bu?"],
["","werden","","olmak (dönüşmek)","Mein Sohn will Arzt werden.","v","Oğlum doktor olmak istiyor."],
["","wichtig","","önemli","Dieses Formular ist sehr wichtig.","a","Bu form çok önemlidir."],
["","wie","","nasıl","Wie heißt du?","x","Adın ne?"],
["","wiederholen","","tekrarlamak","Können Sie das bitte wiederholen?","v","Lütfen bunu tekrarlayabilir misiniz?"],
["das","Wiederhören","","hoşça kal (telefonda)","Danke für Ihren Anruf. Auf Wiederhören!","n","Aramanız için teşekkürler. Hoşça kalın!"],
["das","Wiedersehen","","(Auf Wiedersehen) hoşça kalın","Auf Wiedersehen!","n","Hoşça kalın!"],
["","wie viel","","ne kadar","Wie viel Milch nehmen Sie?","x","Ne kadar süt alırsınız?"],
["","willkommen","","hoş geldiniz","Herzlich willkommen!","a","Hoş geldiniz!"],
["der","Wind","-e","rüzgar","Der Wind kommt aus Osten.","n","Rüzgar doğudan geliyor."],
["","wir","","biz","Wir lernen Deutsch.","x","Almanca öğreniyoruz."],
["","wissen","","bilmek","Weißt du, wie er heißt?","v","Adının ne olduğunu biliyor musun?"],
["","wo","","nerede","Wo waren Sie im Urlaub?","x","Tatilde neredeydiniz?"],
["","woher","","nereden","Woher kommen Sie?","x","Nerelisiniz?"],
["","wohin","","nereye","Wohin fährt dieser Bus?","x","Bu otobüs nereye gidiyor?"],
["","wollen","","istemek","Wollen Sie einen Kaffee trinken?","v","Kahve içmek ister misiniz?"],
["","wunderbar","","harika","Das Essen schmeckt wunderbar.","a","Yemeğin tadı harika."],
["","zahlen","","ödemek","Zahlen, bitte!","v","Hesap lütfen!"],
["die","Zeit","-en","zaman","Ich habe heute keine Zeit.","n","Bugün vaktim yok."],
["","zurzeit","","şu anda","Zurzeit habe ich sehr viel zu tun.","x","Şu anda çok işim var."],
["die","Zigarette","-n","sigara","Wie teuer sind die Zigaretten?","n","Sigaralar ne kadar?"],
["der","Zoll","","gümrük","Wir müssen noch durch den Zoll.","n","Hala gümrükten geçmemiz gerekiyor."],
["","zu","","-e/-a (yön); fazla (zu teuer)","Der Bus fährt zum Bahnhof.","x","Otobüs tren istasyonuna gidiyor."],
["","zufrieden","","memnun","Ich bin mit der Wohnung zufrieden.","a","Daireden memnunum."],
["","zurück","","geri","Einmal Frankfurt und zurück.","x","Frankfurt'a bir gidiş-dönüş, lütfen."],
["","zusammen","","birlikte","Sollen wir zusammen essen gehen?","x","Birlikte akşam yemeğine çıkalım mı?"],
["","zwischen","","arasında","Heidelberg liegt zwischen Frankfurt und Stuttgart.","x","Heidelberg, Frankfurt ile Stuttgart arasında yer almaktadır."],
["","null","","sıfır","Meine Telefonnummer beginnt mit null.","x","Telefon numaram sıfırla başlıyor."],
["","eins","","bir","Der Bus Nummer eins fährt zum Bahnhof.","x","Bir numaralı otobüs istasyona gidiyor."],
["","zwei","","iki","Ich habe zwei Kinder.","x","İki çocuğum var."],
["","drei","","üç","Wir wohnen seit drei Jahren hier.","x","Üç yıldır burada oturuyoruz."],
["","vier","","dört","Wir sind vier Personen.","x","Dört kişiyiz."],
["","fünf","","beş","Ein Kaffee kostet fünf Euro.","x","Bir kahve beş euro."],
["","sechs","","altı","Ich stehe um sechs Uhr auf.","x","Saat altıda kalkıyorum."],
["","sieben","","yedi","Die Woche hat sieben Tage.","x","Haftada yedi gün var."],
["","acht","","sekiz","Der Kurs beginnt um acht Uhr.","x","Kurs saat sekizde başlıyor."],
["","neun","","dokuz","Mein Sohn ist neun Jahre alt.","x","Oğlum dokuz yaşında."],
["","zehn","","on","Ich warte schon zehn Minuten.","x","On dakikadır bekliyorum."],
["","elf","","on bir","Der Zug fährt um elf Uhr ab.","x","Tren saat on birde kalkıyor."],
["","zwölf","","on iki","Ein Jahr hat zwölf Monate.","x","Bir yılda on iki ay var."],
["","dreizehn","","on üç","Meine Tochter ist dreizehn.","x","Kızım on üç yaşında."],
["","vierzehn","","on dört","In vierzehn Tagen habe ich Urlaub.","x","On dört gün sonra tatildeyim."],
["","fünfzehn","","on beş","Der Bus kommt in fünfzehn Minuten.","x","Otobüs on beş dakika sonra geliyor."],
["","sechzehn","","on altı","Das Ticket kostet sechzehn Euro.","x","Bilet on altı euro."],
["","siebzehn","","on yedi","Er ist erst siebzehn Jahre alt.","x","O daha on yedi yaşında."],
["","achtzehn","","on sekiz","Mit achtzehn darf man Auto fahren.","x","On sekiz yaşında araba kullanılabilir."],
["","neunzehn","","on dokuz","Ich wohne in der Goethestraße neunzehn.","x","Goethestraße on dokuz numarada oturuyorum."],
["","zwanzig","","yirmi","Im Kurs sind zwanzig Personen.","x","Kursta yirmi kişi var."],
["","einundzwanzig","","yirmi bir","Claudia ist einundzwanzig.","x","Claudia yirmi bir yaşında."],
["","vierundzwanzig","","yirmi dört","Ein Tag hat vierundzwanzig Stunden.","x","Bir günde yirmi dört saat var."],
["","dreißig","","otuz","Heute haben wir dreißig Grad.","x","Bugün hava otuz derece."],
["","vierzig","","kırk","Mein Vater ist vierzig Jahre alt.","x","Babam kırk yaşında."],
["","fünfzig","","elli","Die Jacke kostet fünfzig Euro.","x","Ceket elli euro."],
["","sechzig","","altmış","Eine Stunde hat sechzig Minuten.","x","Bir saatte altmış dakika var."],
["","siebzig","","yetmiş","Meine Oma ist siebzig.","x","Büyükannem yetmiş yaşında."],
["","achtzig","","seksen","Der Fernseher kostet achtzig Euro.","x","Televizyon seksen euro."],
["","neunzig","","doksan","Der Film dauert neunzig Minuten.","x","Film doksan dakika sürüyor."],
["","(ein)hundert","","(bir) yüz","Das Zimmer kostet hundert Euro pro Nacht.","x","Oda gecelik yüz euro."],
["","hunderteins","","yüz bir","Ich wohne in Zimmer hunderteins.","x","Yüz bir numaralı odada kalıyorum."],
["","zweihundert","","iki yüz","Bis München sind es zweihundert Kilometer.","x","Münih'e iki yüz kilometre var."],
["","(ein)tausend","","(bir) bin","Das Auto kostet tausend Euro.","x","Araba bin euro."],
["","neunzehnhundertneunundneunzig","","bin dokuz yüz doksan dokuz (1999)","Ich bin neunzehnhundertneunundneunzig geboren.","x","Bin dokuz yüz doksan dokuzda doğdum."],
["","zweitausendvierzehn","","iki bin on dört (2014)","Zweitausendvierzehn war ich in Berlin.","x","İki bin on dörtte Berlin'deydim."],
["die","Million","-en","milyon","Berlin hat fast vier Millionen Einwohner.","n","Berlin'in nüfusu yaklaşık dört milyon."],
["die","Milliarde","-n","milyar","Auf der Welt leben acht Milliarden Menschen.","n","Dünyada sekiz milyar insan yaşıyor."],
["","erste","","birinci","Heute ist der erste März.","a","Bugün mart ayının biri."],
["","zweite","","ikinci","Das ist die zweite Frage.","a","Bu ikinci soru."],
["","dritte","","üçüncü","Heute ist mein dritter Arbeitstag.","a","Bugün üçüncü iş günüm."],
["","vierte","","dördüncü","Die vierte Aufgabe ist leicht.","a","Dördüncü görev kolay."],
["","usw.","","vb.","Ich kaufe Brot, Milch, Käse usw.","x","Ekmek, süt, peynir vb. alıyorum."],
["","halb","","yarım","Es ist halb drei.","x","Saat iki buçuk."],
["","ein halb","","yarım","Ich möchte ein halbes Kilo Tomaten.","x","Yarım kilo domates istiyorum."],
["das","Viertel","-","çeyrek","Es ist Viertel nach drei.","n","Saat üçü çeyrek geçiyor."],
["","ein Viertel","","çeyrek","Ich esse nur ein Viertel von der Pizza.","x","Pizzanın sadece çeyreğini yiyorum."],
["die","Sekunde","-n","saniye","Warte bitte eine Sekunde.","n","Lütfen bir saniye bekle."],
["die","Minute","-n","dakika","Es ist fünf Minuten vor eins.","n","Saat bire beş var."],
["die","Woche","-n","hafta","Diese Woche lerne ich Deutsch.","n","Bu hafta Almanca öğreniyorum."],
["das","Jahr","-e","yıl","Dieses Jahr mache ich Urlaub in Spanien.","n","Bu yıl İspanya'da tatil yapıyorum."],
["der","Tag","-e","gün","Der Tag ist heute sehr schön.","n","Bugün çok güzel bir gün."],
["der","Wochentag","-e","hafta içi günü","Montag ist ein Wochentag.","n","Pazartesi bir hafta içi günüdür."],
["der","Sonntag","-e","pazar","Am Sonntag besuche ich meine Eltern.","n","Pazar günü ailemi ziyaret ediyorum."],
["der","Montag","-e","pazartesi","Am Montag beginnt mein Deutschkurs.","n","Almanca kursum pazartesi başlıyor."],
["der","Dienstag","-e","salı","Am Dienstag gehe ich zum Arzt.","n","Salı günü doktora gidiyorum."],
["der","Mittwoch","-e","çarşamba","Am Mittwoch arbeite ich nicht.","n","Çarşamba günü çalışmıyorum."],
["der","Donnerstag","-e","perşembe","Am Donnerstag treffen wir unsere Freunde.","n","Perşembe günü arkadaşlarımızla buluşuyoruz."],
["der","Freitag","-e","cuma","Am Freitag gehe ich ins Kino.","n","Cuma günü sinemaya gidiyorum."],
["der","Samstag","-e","cumartesi","Am Samstag kaufe ich ein.","n","Cumartesi günü alışveriş yapıyorum."],
["der","Sonnabend","-e","cumartesi","Am Sonnabend besuchen wir Oma.","n","Cumartesi günü büyükannemizi ziyaret ediyoruz."],
["das","Wochenende","-n","hafta sonu","Am Wochenende schlafe ich lange.","n","Hafta sonu geç saate kadar uyurum."],
["der","Morgen","-","sabah","Am Morgen trinke ich eine Tasse Kaffee.","n","Sabah bir fincan kahve içiyorum."],
["der","Vormittag","-e","öğleden önce","Am Vormittag habe ich einen Deutschkurs.","n","Öğleden önce Almanca kursum var."],
["der","Mittag","-e","öğle","Um zwölf Uhr machen wir Mittag.","n","Saat on ikide öğle yemeği yiyoruz."],
["der","Nachmittag","-e","öğleden sonra","Am Nachmittag gehen wir spazieren.","n","Öğleden sonra yürüyüşe çıkıyoruz."],
["der","Abend","-e","akşam","Am Abend sehe ich einen Film.","n","Akşam bir film izliyorum."],
["die","Nacht","¨-e","gece","In der Nacht schlafe ich acht Stunden.","n","Gece sekiz saat uyuyorum."],
["der","Januar","-","ocak","Im Januar ist es oft kalt.","n","Ocak ayında hava sık sık soğuk olur."],
["der","Februar","-","şubat","Der Februar hat normalerweise 28 Tage.","n","Şubat normalde 28 gündür."],
["der","März","-","mart","Im März beginnt der Frühling.","n","Mart ayında ilkbahar başlar."],
["der","April","-","nisan","Im April regnet es oft.","n","Nisan ayında sık sık yağmur yağar."],
["der","Mai","-","mayıs","Im Mai blühen viele Blumen.","n","Mayıs ayında birçok çiçek açar."],
["der","Juni","-","haziran","Im Juni sind die Tage lang.","n","Haziran ayında günler uzundur."],
["der","Juli","-","temmuz","Im Juli machen wir Urlaub.","n","Temmuz ayında tatile çıkıyoruz."],
["der","August","-","ağustos","Im August besuchen wir unsere Freunde.","n","Ağustos ayında arkadaşlarımızı ziyaret ediyoruz."],
["der","September","-","eylül","Im September beginnt die Schule.","n","Eylül ayında okul başlar."],
["der","Oktober","-","ekim","Im Oktober werden die Tage kürzer.","n","Ekim ayında günler kısalır."],
["der","November","-","kasım","Im November ist es oft kühl.","n","Kasım ayında hava sık sık serin olur."],
["der","Dezember","-","aralık","Im Dezember feiern wir Weihnachten.","n","Aralık ayında Noel'i kutluyoruz."],
["der","Frühling","-e","ilkbahar","Im Frühling blühen die Blumen.","n","İlkbaharda çiçekler açar."],
["das","Frühjahr","-e","ilkbahar","Im Frühjahr machen wir eine Reise.","n","İlkbaharda bir seyahate çıkıyoruz."],
["der","Sommer","-","yaz","Im Sommer fahren wir ans Meer.","n","Yazın deniz kenarına gidiyoruz."],
["der","Herbst","-e","sonbahar","Im Herbst fallen die Blätter.","n","Sonbaharda yapraklar dökülür."],
["der","Winter","-","kış","Im Winter schneit es manchmal.","n","Kışın bazen kar yağar."],
["der","Euro","-s","avro","Ein Euro hat hundert Cent.","n","Bir euro yüz senttir."],
["der","Cent","-s","sent","Das Brötchen kostet fünfzig Cent.","n","Küçük ekmek elli sent."],
["der","Meter","-","metre","Mein Sohn ist ein Meter fünfzehn groß.","n","Oğlumun boyu bir metre on beş."],
["der","Zentimeter","-","santimetre","Der Tisch ist achtzig Zentimeter hoch.","n","Masa seksen santimetre yüksekliğinde."],
["der","Kilometer","-","kilometre","Bis zum Bahnhof sind es zwei Kilometer.","n","İstasyona iki kilometre var."],
["der","Quadratmeter","-","metrekare","Die Wohnung hat sechzig Quadratmeter.","n","Daire altmış metrekare."],
["das","Grad","-","derece","Heute ist es ein Grad unter null.","n","Bugün hava sıfırın altında bir derece."],
["","minus","","eksi","Heute Nacht sind es minus fünf Grad.","x","Bu gece hava eksi beş derece."],
["","plus","","artı","Morgen haben wir plus vier Grad.","x","Yarın hava artı dört derece."],
["das","Prozent","-","yüzde","Heute gibt es zwanzig Prozent auf alle Schuhe.","n","Bugün tüm ayakkabılarda yüzde yirmi indirim var."],
["der","Liter","-","litre","Ich kaufe einen Liter Milch.","n","Bir litre süt alıyorum."],
["das","Gramm","-","gram","Ich möchte zweihundert Gramm Käse.","n","İki yüz gram peynir istiyorum."],
["das","Pfund","-e","yarım kilo","Ein Pfund Tomaten, bitte.","n","Yarım kilo domates lütfen."],
["das","Kilogramm","-","kilogram","Der Koffer wiegt zwanzig Kilogramm.","n","Bavul yirmi kilogram."],
["das","Kilo","-s","kilo","Ein Kilo Kartoffeln kostet zwei Euro.","n","Bir kilo patates iki euro."],
["","Deutschland","","Almanya","Deutschland liegt in Europa.","x","Almanya Avrupa'da yer alır."],
["der","Deutsche","-n","Alman (erkek)","Mein Nachbar ist ein Deutscher.","n","Komşum bir Alman."],
["die","Deutsche","-n","Alman (kadın)","Meine Lehrerin ist eine Deutsche.","n","Öğretmenim bir Alman."],
["","deutsch","","Alman; Almanca","Die deutsche Sprache ist interessant.","a","Alman dili ilginçtir."],
["","Europa","","Avrupa","Europa ist ein großer Kontinent.","x","Avrupa büyük bir kıtadır."],
["der","Europäer","-","Avrupalı","Viele Europäer reisen gern.","n","Birçok Avrupalı seyahat etmeyi sever."],
["","europäisch","","Avrupalı; Avrupa'ya ait","Berlin ist eine europäische Stadt.","a","Berlin bir Avrupa şehridir."],
["die","Türkei","","Türkiye","Die Türkei liegt zwischen Europa und Asien.","n","Türkiye, Avrupa ile Asya arasında yer alır."],
["der","Türke","-n","Türk (erkek)","Der Türke kommt aus Ankara.","n","Türk adam Ankara'dan geliyor."],
["die","Türkin","-nen","Türk (kadın)","Die Türkin spricht Deutsch und Türkisch.","n","Türk kadın Almanca ve Türkçe konuşuyor."],
["","türkisch","","Türk; Türkçe","Ich esse gern türkisches Essen.","a","Türk yemeklerini severek yerim."],
["","Finnland","","Finlandiya","Finnland liegt im Norden Europas.","x","Finlandiya Avrupa'nın kuzeyinde yer alır."],
["der","Finne","-n","Fin (erkek)","Der Finne wohnt in Helsinki.","n","Finli adam Helsinki'de yaşıyor."],
["die","Finnin","-nen","Fin (kadın)","Die Finnin spricht Finnisch.","n","Finli kadın Fince konuşuyor."],
["","finnisch","","Fin; Fince","Finnisch klingt anders als Deutsch.","a","Fince, Almancadan farklı duyulur."],
["","Mexiko","","Meksika","Mexiko ist ein großes Land.","x","Meksika büyük bir ülkedir."],
["der","Mexikaner","-","Meksikalı (erkek)","Der Mexikaner wohnt in Mexiko.","n","Meksikalı adam Meksika'da yaşıyor."],
["die","Mexikanerin","-nen","Meksikalı (kadın)","Die Mexikanerin spricht Spanisch.","n","Meksikalı kadın İspanyolca konuşuyor."],
["","mexikanisch","","Meksikalı; Meksika'ya ait","Wir essen heute mexikanisches Essen.","a","Bugün Meksika yemeği yiyoruz."],
["","schwarz","","siyah","Die Nacht ist schwarz.","a","Gece siyahtır."],
["","grau","","gri","Der Himmel ist heute grau.","a","Bugün gökyüzü gri."],
["","blau","","mavi","Das Meer ist blau.","a","Deniz mavidir."],
["","grün","","yeşil","Das Gras ist grün.","a","Çimenler yeşildir."],
["","weiß","","beyaz","Der Schnee ist weiß.","a","Kar beyazdır."],
["","rot","","kırmızı","Die Tomate ist rot.","a","Domates kırmızıdır."],
["","gelb","","sarı","Die Banane ist gelb.","a","Muz sarıdır."],
["","braun","","kahverengi","Der Tisch ist braun.","a","Masa kahverengidir."],
["der","Norden","-","kuzey","Im Norden ist es heute kalt.","n","Kuzeyde bugün hava soğuk."],
["der","Süden","-","güney","Im Süden ist das Wetter warm.","n","Güneyde hava sıcaktır."],
["der","Westen","-","batı","Im Westen geht die Sonne unter.","n","Güneş batıda batar."],
["der","Osten","-","doğu","Im Osten geht die Sonne auf.","n","Güneş doğuda doğar."]
].map(r=>({art:r[0],w:r[1],pl:r[2],tr:r[3],ex:r[4],type:r[5],exTr:r[6],id:r[0]+"|"+r[1]}));

/* Yazımı değişen kelimeler: eski kimlik -> yeni kimlik */
const ID_ALIASES = {
  "|Achtung": "die|Achtung",
  "|all-": "|alle",
  "|ander-": "|andere",
  "|best-": "|am besten",
  "|dein-": "|dein",
  "|dies-": "|dieser",
  "|ein-": "|ein, eine",
  "|Feier-": "der|Feiertag",
  "|freuen": "|sich freuen",
  "|Grad (Celsius)": "das|Grad",
  "|jed-": "|jeder",
  "|(Kredit)-Karte": "die|Kreditkarte",
  "|letzt-": "|letzte",
  "|lieb-": "|lieb",
  "|meist-": "|meiste",
  "|nächst-": "|nächste",
  "|Satz": "der|Satz",
  "|unser-": "|unser",
  "|vorstellen": "|sich vorstellen",
  "|welch-": "|welcher",
  "|Kilo(gramm)": "das|Kilo",
  "der|Deutscher": "der|Deutsche"
};
